envoyproxy/ai-gateway

README.md

Adding a one liner description to the project.

Initial README.md update with one-liner description.

---

README.md

Adding information on how to get involved in the project to project README.

Adding how to get involved information to project README

---

CONTRIBUTING.md

This adds an initial CONTRIBUTING.md with some comments
about DCO as well as a generic PR review processes.

Adds simple CONTRIBUTING.md

---

.github/workflows/commit.yaml
.github/workflows/docker_builds_template.yaml

This is a follow up on #18 - verified it's working:
* https://github.com/envoyproxy/ai-gateway/pkgs/container/ai-gateway%2Fcontroller
* https://github.com/envoyproxy/ai-gateway/pkgs/container/ai-gateway%2Fextproc

ci: fixes docker push command

---

.codespell.skip
Makefile
Makefile.tools.mk
internal/apischema/openai/openai.go
manifests/charts/ai-gateway-helm/crds/aigateway.envoyproxy.io_llmroutes.yaml

Fixes: https://github.com/envoyproxy/ai-gateway/issues/28

chore: enable codespell check

---

.github/workflows/commit.yaml
.github/workflows/tests_using_secrets.yaml
.gitignore
Makefile
cmd/controller/main.go
internal/controller/controller.go
internal/controller/llmroute.go
tests/cel-validation/main_test.go
tests/controller/controller_test.go
tests/envtest.go
tests/extproc/extproc_test.go

This simply scaffolds the controller envtets,
and only adds the test for controller.StartControllers
function on basic scenario. The follow PRs will add more
test cases.

test: adds initial controller tests

---

internal/controller/controller.go
internal/controller/llmbackend.go
internal/controller/llmbackend_test.go
internal/controller/llmroute.go
internal/controller/sink.go
internal/controller/sink_test.go
tests/cel-validation/main_test.go
tests/controller/controller_test.go
tests/envtest.go

This is a follow up on #75, and increases the 
envtest coverage for all controllers.

tests: adds additional controller tests

---

tests/extproc/extproc_test.go

tests: adds streaming endpoint test case for extproc

---

.github/workflows/commit.yaml

Applies the same fix as in #120 to test_e2e

ci: fixes check out issue in test_e2e with fork

---

.yamllint
.yamllint.ignore

Ignore .gitignore from yamllint

---

filterconfig/filterconfig.go
filterconfig/filterconfig_test.go
internal/controller/sink.go
internal/controller/sink_test.go
internal/extproc/backendauth/aws.go
internal/extproc/backendauth/aws_test.go
tests/extproc/extproc_test.go
tests/extproc/real_providers_test.go

Replace ENV AWS auth with credential file

feat: implement aws credential file auth

---

filterconfig/filterconfig.go

Updating comments LLMRoute -> AIGatewayRoute

chore: replace llmroute with aigatewayroute

---

api/v1alpha1/api.go
examples/basic/basic.yaml
internal/controller/sink.go
internal/controller/sink_test.go
manifests/charts/ai-gateway-helm/crds/aigateway.envoyproxy.io_backendsecuritypolicies.yaml
tests/e2e/basic_test.go
tests/e2e/e2e_test.go

controller: fixes volume mounts and add e2e with real backends

---

CONTRIBUTING.md

This adds the local development guide as we have started
seeing more incoming PRs into this repository.
Closes #78 and supersedes a part of #179

docs: local dev guide in CONTRIBUTING.md

---

CONTRIBUTING.md

This CONTRIBUTING.md by adding some of the
missing dependencies.
Follow up on #180

docs: fixes CONTRIBUTING.md

---

netlify.toml

Updating the netlify.toml configurations
I have validated the configurations work with Netlify here: https://celebrated-zabaione-b8a322.netlify.app/
The purpose and function of the config:
- setting the `base` as `site/` which ensures netlify builds and deploys **only happen** when there's changes to the site directory, this is a special netlify config
- setting up a `context.deploy-preview` so we get preview deploys for PRs when there are changes to the `site/` directory
- updating headers with additional security headers to improve site

Site updates to facilitate netlify deploys

---

build-website.sh

This was added in #178 but become obsolete in #183.

chore: removes build-website.sh

---

.github/workflows/commit.yaml
.github/workflows/docker_builds_template.yaml

This fixes the docker push job broken in #198.
follow up on #198

ci: fixes docker push job

---

Makefile
Makefile.tools.mk
site/crd-ref-docs/config.yaml
site/crd-ref-docs/templates/README
site/crd-ref-docs/templates/gv_details.tpl
site/crd-ref-docs/templates/gv_list.tpl
site/crd-ref-docs/templates/type.tpl
site/crd-ref-docs/templates/type_members.tpl
site/docs/api.md
site/docs/getting_started.md

This generates the API documentation hosted on the site.
#29

docs: generate API documentation

---

examples/basic/basic.yaml
site/docs/getting_started.md
tests/doctest/doctest.go
tests/doctest/getting_started_test.go
tests/e2e/basic_test.go

This completes the initial getting_started doc.
#29

docs: finishes the initial getting_started 

---

.github/dependabot.yml

This configures the dependabot for the site directory.

ci: set ups dependabot for /site 

---

CONTRIBUTING.md
README.md

docs: modifies CONTRIBUTING/README

---

site/docs/index.md

Make some minor Markdown formatting changes for readability and linting including wrapping long lines and having one space between paragraphs and lists.

docs: add helpful links to overview page

---

site/docusaurus.config.ts
site/src/pages/index.tsx

Adding Google analytics tag and making the site description use the tagline from the config.

docs: Adding Google analytics tag, updating site meta description.

---

site/docs/getting-started/prerequisites.md

**Commit Message**: This commit moves the required tools subsection to the top of the "Prerequisite" page. Later in the page we ask users to use kubectl and helm commands so we need to verify installations first. 
**Related Issues/PRs (if applicable)**: n/a
**Special notes for reviewers (if applicable)**: n/a

docs: Moved Required tools section of Prerequisite to the top

---

.testcoverage.yml
internal/controller/ai_gateway_route.go
internal/controller/ai_gateway_route_test.go
internal/controller/ai_service_backend_test.go
internal/controller/backend_security_policy_test.go
internal/controller/controller.go
internal/controller/secret_test.go
internal/controller/sink.go
internal/controller/sink_test.go

This increases the test coverage of controller
package. The only exception left is the main
controller.go file which requires a relatively large
refactoring.

test: adds more coverage of internal/controller

---

.testcoverage.yml
internal/apischema/awsbedrock/awsbedrock.go
internal/apischema/openai/openai_test.go

This removes the test coverage exception
of apischema package by adding more
unit tests.

test: removes apischema coverage exception

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr_title_check.yaml

This makes the PR style check stricter than before:
* The description's first line must be `**Commit Message**`
* The PR title length must be less than 53 characters

chore: fixes PR style check

---

.github/workflows/pr_style_check.yaml

This refactors the PR style check github workflow.
* Renamed the file to match the workflow name.
* Split the description checks into multiple runs.

ci: cleanup PR Style Check GHA

---

.github/workflows/style.yaml
Makefile

Apparently, the message was clear enough

chore: more clarify what to do on Style check failure

---

.github/workflows/style.yaml
.github/workflows/tests.yaml

This puts stricter permissions on Tests and Style
GitHub Actions workflows.

ci: stricter permissions on style/tests workflows

---

examples/token_ratelimit/token_ratelimit.yaml
tests/e2e/token_ratelimit_test.go

This add a CEL expression token usage example that is
missing from the example as well as the e2e test.
closes #257

examples: adds token rate limit

---

internal/controller/controller.go
internal/controller/sink.go
internal/controller/sink_test.go

This refactors the controller package to eliminate
all the context.Background usages in the main code
path.

controller: eliminates context.Background

---

api/v1alpha1/api.go
manifests/charts/ai-gateway-helm/crds/aigateway.envoyproxy.io_aigatewayroutes.yaml
site/docs/api.md

This adds additional doc comments on AIGatewayRoute resource 
about which k8s resources will be created by Envoy AI Gateway.
Closes #258

docs: more comment about generated resources in API

---

Makefile.tools.mk

This updates several tool dependencies.

chore: updates tools

---

site/package-lock.json
site/package.json

Upgrading to docusaurus to version 3.7.0 and related dependencies.

chore: upgrade docusaurus version to 3.7.0

---

site/docs/getting-started/basic-usage.md
site/docs/getting-started/index.md
site/docs/getting-started/installation.md
site/docs/getting-started/prerequisites.md
site/package-lock.json
site/package.json
site/src/components/ApiField.tsx
site/src/css/custom.css
site/src/theme/MDXComponents.tsx

Address CSS styling issues and React component issues.
This fixes issues related to styling and React components.
For example, the code copy button is currently broken on the site. This PR fixes that.

docs: fixing React component and CSS issues

---

site/docs/capabilities/usage-based-ratelimiting.md

The model name is extracted by AI Gateway filter, not the one explicitly added by downstream clients.
Follow up on #260

docs: tweaks rate limit doc on model

---

.github/workflows/pr_style_check.yaml

Use regex to check.
Fixes #267

chore: check markdown format link

---

.github/workflows/pr_style_check.yaml

Previously, square brackets without being followed by () was also rejected. This fixes the regex and allows it.
Follow up on #322

chore: fixes pr_style_check.yaml

---

Makefile

Previously, the .bin directly was not cleared, so this fixes it.
Follow up on #329

chore: modifies make clean

---

tests/extproc/real_providers_test.go

e2e: add test for the models endpoint using the openai client
Related to https://github.com/envoyproxy/ai-gateway/pull/325
N/A

e2e: add models test using the openai client

---

internal/extproc/models_processor_test.go
internal/extproc/server_test.go
tests/e2e/basic_test.go
tests/e2e/e2e_test.go

Use t.Context instead of Background whenever possible.
Follow up on #329

test: use t.Context whenever possible

---

.github/workflows/pr_style_check.yaml

Add site and blog to allowed PR prefixes

ci: add blog and site to PR check prefixes

---

examples/basic/localmodel.yaml
site/docs/getting-started/connect-providers/localmodel.md

This commit adds documentation for using the DeepSeek R1 model (running locally considering Platform Keys are not available) with Envoy AI Proxy.
Supersedes #287

docs: added DeepSeek configuration

---

netlify.toml

Fix the headers set via Netlify so the google analytics script functions to capture analytics.

site: fix security header to allow google analytics

---

site/src/components/HomepageFeatures/styles.module.css
site/src/css/custom.css
site/src/pages/index.tsx

- Add GitHub button on hero
- Change Join Community button to Get Started
- Make feature images smaller
- Fix top margin for header text

site: add improved home page styling

---

internal/controller/backend_security_policy.go

Previously, the mutex was not taken on the OIDC cache, but after #364, it is necessary as the sync function of each controller now might be invoked by other controllers.

controller: mutex on oidcTokenCache

---

site/docs/getting-started/connect-providers/index.md
site/docs/getting-started/connect-providers/localmodel.md

Tell user to download `localmodel.yaml` first before kubectl applying it. Make some minor Markdown formatting improvements.

docs: add missing step to local model provider page

---

site/src/css/custom.css

Fix CSS styling for button placement and text size on the home page hero for small screens.

site: fix hero button placement on homepage for small screens

---

site/docs/concepts/architecture/control-plane.md

Be more specific what K8s resources the controller watches.

docs: clarify what the controller watches

---

site/src/css/custom.css

Ensure hover styling has same border-radius, so the buttons maintain the shape when hovering.

site: fix homepage button hover styling

---

.github/workflows/tests.yaml

This is enabling the tests workflow on release/** branches for the future backports etc.

ci: enable tests on release/** branches

---

internal/controller/backend_security_policy.go
internal/controller/backend_security_policy_test.go
internal/controller/controller.go
tests/controller/controller_test.go

Adding test TestBackendSecurityPolicyController and exporting BackendSecurityPolicy + NewBackendSecurityPolicy

test: add TestBackendSecurityPolicyController

---

site/blog/authors.yml

Fix link to Alexa's LinkedIn profile in authors file.

site: fix alexa's linkedin link in authors.yml

---

site/versioned_docs/version-0.1.0/getting-started/basic-usage.md
site/versioned_docs/version-0.1.0/getting-started/connect-providers/index.md
site/versioned_docs/version-0.1.0/getting-started/index.md
site/versioned_docs/version-0.1.0/getting-started/installation.md

In versioned docs, the URL of a yaml must point to the tagged permalink.
Follow up on #421

docs: pin yaml urls to tags

---

CONTRIBUTING.md

This updates CONTRIBUTING.md so that it has more detailed information about contributing to this project.

docs: updates CONTRIBUTING.md

---

internal/controller/ai_gateway_route.go
internal/controller/ai_gateway_route_test.go

This removes the left over implementation from when we had config sink. 
Follow up on #364

controller: removes the leftover from config sink

---

site/blog/2025-02-25-first-ai-gw-release.md
site/src/pages/release-notes.md
site/versioned_docs/version-0.1/getting-started/basic-usage.md
site/versioned_docs/version-0.1/getting-started/connect-providers/index.md
site/versioned_docs/version-0.1/getting-started/index.md
site/versioned_docs/version-0.1/getting-started/installation.md

Update documentation to be up to date with latest release patch. https://github.com/envoyproxy/ai-gateway/releases/tag/v0.1.1
https://github.com/envoyproxy/ai-gateway/commit/3ea774e125712f0173695a275d78d9acef59845a

site: bump patch version to v0.1.1

---

internal/controller/ai_gateway_route.go
internal/controller/ai_gateway_route_test.go
manifests/charts/ai-gateway-helm/values.yaml

Fix syncing extproc image tag in ai gateway routing reconciliation. 
Fixes #446

controller: fix syncing extproc image tag

---

.github/workflows/docker_builds_template.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml

Backport docker hub changes needed to run CI.

backport: ci: update dockerhub user (#441)

---

site/versioned_docs/version-0.1/getting-started/index.md
site/versioned_docs/version-0.1/getting-started/prerequisites.md

Envoy Gateway has released the CVE fixes recently.

docs: bumps EG version to 1.3.1

---

tests/extproc/extproc_test.go

This removes the low log levels accidentally enabled in #468 
Follow up on #468

test: removes unnecessary logs

---

cmd/aigw/testdata/translate_basic.out.yaml

This removes the unnecessary fields from the expected output of translation test case.
Contributes to #412

cli: removes unneeded fields in translation test

---

Makefile
cmd/extproc/mainlib/main.go
examples/extproc_custom_metrics/README.md
examples/extproc_custom_metrics/main.go
examples/extproc_custom_router/main.go
filterapi/x/x.go
internal/extproc/chatcompletion_processor.go
internal/extproc/mocks_test.go
internal/metrics/chat_completion_metrics.go
internal/metrics/chat_completion_metrics_test.go
tests/extproc/custom_extproc_test.go

extproc: allow building with custom metric implementations
N/A
N/A

extproc: allow building with custom metric implementations

---

cmd/extproc/mainlib/main.go
cmd/extproc/mainlib/main_test.go
go.mod
go.sum
internal/apischema/openai/openai.go
internal/apischema/openai/openai_test.go
internal/extproc/chatcompletion_processor.go
internal/extproc/chatcompletion_processor_test.go
internal/extproc/mocks_test.go
internal/extproc/translator/openai_awsbedrock.go
internal/extproc/translator/openai_awsbedrock_test.go
internal/extproc/translator/openai_openai.go
internal/extproc/translator/openai_openai_test.go
internal/extproc/translator/translator.go
internal/metrics/chat_completion_metrics.go
internal/metrics/chat_completion_metrics_test.go
internal/metrics/genai.go
tests/extproc/extproc_test.go
tests/extproc/testupstream_test.go

PR to backport `mockChatCompletionMetrics`, chat completion stream fix, and openai content type.
Including:
- #459 (468 uses mock components introduced here)
- #468 
- #486

backport: completion stream + metrics and assistant content

---

site/blog/2025-02-25-first-ai-gw-release.md
site/src/pages/release-notes.md
site/versioned_docs/version-0.1/getting-started/basic-usage.md
site/versioned_docs/version-0.1/getting-started/connect-providers/index.md
site/versioned_docs/version-0.1/getting-started/index.md
site/versioned_docs/version-0.1/getting-started/installation.md

Updating for newest release: https://github.com/envoyproxy/ai-gateway/releases/tag/v0.1.3
https://github.com/envoyproxy/ai-gateway/pull/497

site: update to use v0.1.3

---

internal/controller/tokenprovider/azure_token_provider.go
internal/controller/tokenprovider/azure_token_provider_test.go
manifests/charts/ai-gateway-helm/values.yaml

Add proxy URL option for Azure authentication.
Related PR: #445

feat: add proxy URL option for Azure authentication 

---

cmd/aigw/ai-gateway-default-resources.yaml
site/docs/cli/index.md
site/docs/cli/installation.md
site/docs/cli/run.md
site/docs/cli/translate.md

This adds a basic documentation about `aigw` CLi recently implemented merged.
Closes #412

docs: adds aigw CLI basic documentation

---

site/blog/2025-02-25-first-ai-gw-release.md
site/src/pages/release-notes.md
site/versioned_docs/version-0.1/getting-started/basic-usage.md
site/versioned_docs/version-0.1/getting-started/connect-providers/index.md
site/versioned_docs/version-0.1/getting-started/index.md
site/versioned_docs/version-0.1/getting-started/installation.md

Setting to use the latest release! Apologies for the delay.
#524

site: bump to use release v0.1.5

---

site/docs/capabilities/inference-extension.md

This adds a new page under capability that documents the inference extension API usage.
Contributes to #423

docs: adds Inference Extension page

---

cmd/aigw/run_test.go
go.mod
go.sum
internal/apischema/openai/openai_test.go
tests/e2e/basic_test.go
tests/e2e/translation_testupstream_test.go
tests/extproc/custom_extproc_test.go
tests/extproc/real_providers_test.go
tests/extproc/testupstream_test.go

to 0.1.0-beta.6 from 0.1.0-alpha.65
closes #545

chore: upgrade github.com/openai/openai-go

---

site/src/components/HomepageFeatures/index.tsx

Address link issues on homepage feature of 0.1 release
Fixes https://github.com/envoyproxy/ai-gateway/issues/546

site: fix links on homepage feature of 0.1 release

---

.github/workflows/tests.yaml

ci: updates Envoy version to v1.34

---

.github/workflows/tests.yaml

ci: updates EG to v1.4.0-rc.2 to verify the behavior

---

.github/workflows/tests.yaml

This removes the label based execution of workflows in tests.yaml

ci: removes label based execution

---

internal/extensionserver/extensionserver.go
internal/extensionserver/extensionserver_test.go
internal/extproc/server.go
internal/extproc/server_test.go
tests/extproc/envoy.yaml

Fix typo for endpoint filter metadata from aigateawy to aigateway

extproc: fix aigateway typo for filter metadata

---

.github/workflows/pr_style_check.yaml

This adds a new prefix "refactor" to the allowed list.

ci: allow "refactor" as a commit prefix

---

manifests/charts/ai-gateway-helm/templates/admission_webhook.yaml
manifests/charts/ai-gateway-helm/values.yaml

This PR is to enable cert-manger to mange the certificates of mutating-webhook-server.

controller: enable cert-manger for mutating-webhook-server

---

tests/e2e/provider_fallback_test.go

This fixes Test_Examples_ProviderFallback so that it will wait for the gateway properly. Previously, the manifest was applied unnecessarily twice and it only waited for the gateway to be up and running for the first apply hence there was a flake.
Closes #647

test: fixes flake of Test_Examples_ProviderFallback

---

cmd/controller/main.go
cmd/controller/main_test.go
internal/controller/controller.go
manifests/charts/ai-gateway-helm/templates/deployment.yaml
manifests/charts/ai-gateway-helm/values.yaml
tests/e2e/e2e_test.go

This removes the unused flag as a preparation for v0.2 release.

chore: removes unused flags for v0.2

---

site/docs/index.md

Updating the overview page as we have passed the initial release and are approaching our second release.

docs: update overview docs page

---

site/docs/concepts/architecture/system-architecture.md

This updates the high level system architecture page to reflect what has changed since v0.1 as well as fixes the wrong comment about rate limit service being configured by AI Gateway. In fact, it has been configured by EG.

site: updates system-architecture page

---

site/src/data/releases/v0.2.json
site/src/pages/release-notes/v0.2.mdx

This adds a release note on v0.2.1 released yesterday.

site: adds release note on v0.2.1

---

site/docs/concepts/architecture/control-plane.md
site/docs/concepts/architecture/data-plane.md

This updates the architecture pages so that the diagrams there reflect more accurate information.

docs: updates diagrams on architecture page

---

site/docs/concepts/architecture/control-plane.md
site/docs/concepts/architecture/data-plane.md
site/docs/concepts/architecture/index.md
site/docs/concepts/architecture/system-architecture.md
site/docs/getting-started/index.md
site/versioned_docs/version-0.2/capabilities/fallback.md
site/versioned_docs/version-0.2/capabilities/metrics.md
site/versioned_docs/version-0.2/concepts/architecture/control-plane.md
site/versioned_docs/version-0.2/concepts/architecture/data-plane.md
site/versioned_docs/version-0.2/concepts/architecture/index.md
site/versioned_docs/version-0.2/concepts/architecture/system-architecture.md
site/versioned_docs/version-0.2/getting-started/basic-usage.md
site/versioned_docs/version-0.2/getting-started/connect-providers/index.md
site/versioned_docs/version-0.2/getting-started/index.md
site/versioned_docs/version-0.2/getting-started/installation.md
site/versioned_docs/version-0.2/getting-started/prerequisites.md

This completes the architecture page updates following the series of diagram updates in the last few weeks. This reflects these changes in the v0.2 versioned doc as well.
This also fixes the pages in v0.2 doc that still used main/latest tag instead of v0.2.

site: completes v0.2 doc update

---

api/v1alpha1/api.go
manifests/charts/ai-gateway-crds-helm/templates/aigateway.envoyproxy.io_backendsecuritypolicies.yaml
tests/crdcel/main_test.go
tests/crdcel/testdata/backendsecuritypolicies/apikey_with_aws_credentials.yaml
tests/crdcel/testdata/backendsecuritypolicies/apikey_with_azure_credentials.yaml
tests/crdcel/testdata/backendsecuritypolicies/apikey_with_gcp_credentials.yaml
tests/crdcel/testdata/backendsecuritypolicies/apikey_with_nil_configuration.yaml
tests/crdcel/testdata/backendsecuritypolicies/aws_credential_file.yaml
tests/crdcel/testdata/backendsecuritypolicies/aws_oidc.yaml
tests/crdcel/testdata/backendsecuritypolicies/aws_with_azure_credentials.yaml
tests/crdcel/testdata/backendsecuritypolicies/azure_with_gcp_credentials.yaml
tests/crdcel/testdata/backendsecuritypolicies/basic.yaml
tests/crdcel/testdata/backendsecuritypolicies/gcp_with_apikey.yaml

fix: invalid bsp spec will cause panic
Fixes: #739

fix: invalid bsp spec will cause panic

---

Makefile

refactor: extensible make target
Before: make help target is not extensible and writen by hand. New targets cannot track there, and no group for targets.
After:

refactor: extensible make target

---

.github/workflows/osv-scanner.yaml

ci: add osv-scanner workflows

---

examples/README.md

Add README.md under `/examples`

docs: add example guides

---

docs/proposals/003-epp-integration-proposal/proposal.md

This PR updates epp integration proposal outdated logics.

docs: update epp outdated logics

---

Makefile

This PR is to make  test-e2e logs visible in local.

chore: make test-e2e logs visible

---

.github/workflows/build_and_test.yaml
cmd/aigw/ai-gateway-default-resources.yaml
cmd/aigw/run_test.go

This adds an additional test to aigw run command so that we can verify that setting the default route is possible. 
Closes #612

cli: adds default route test

---

internal/controller/gateway_test.go

test: increase the GCP credential coverage

---

internal/controller/backend_security_policy.go

This commit fixes log panic in  BackendSecurityPolicyController
Fixes https://github.com/envoyproxy/ai-gateway/issues/877
None

fix: panic in  BackendSecurityPolicyController

---

examples/provider_fallback/fallback.yaml
site/docs/capabilities/traffic/provider-fallback.md

This PR clean-up after adding numAttemptsPerPriority.

docs: clean-up after numAttemptsPerPriority

---

site/docusaurus.config.ts

Fixing the setting in Docusaurus, which is causing a bug when clicking to share blogs
n/a
This is currently causing a bug when clicking to share blogs

site: fix site url setting

---

internal/extproc/translator/gemini_helper.go
internal/extproc/translator/openai_gcpanthropic.go
internal/extproc/translator/openai_gcpvertexai.go
internal/extproc/translator/openai_gcpvertexai_test.go
internal/extproc/translator/translator.go
internal/extproc/translator/util.go
internal/extproc/translator/util_test.go
tests/extproc/testupstream_test.go
tests/internal/testupstreamlib/testupstream.go
tests/internal/testupstreamlib/testupstream/main.go
tests/internal/testupstreamlib/testupstream/main_test.go

Add streaming support for Gemini API.
This PR implements transformations from gemini-streaming-chunks to openai-chunks
Issues:
- https://github.com/envoyproxy/ai-gateway/issues/609
- https://github.com/envoyproxy/ai-gateway/issues/864

feat: add streaming support for GCP Vertex AI

---

docs/proposals/003-epp-integration-proposal/proposal.md

1. This PR updates the EPP integration design logics.
2. This PR addes the request flow diagram for EPP integration.

docs: update epp design logics

---

site/docs/capabilities/inference/aigatewayroute-inferencepool.md

This PR updates the AIGatewayRoute + InferencePool demo, follow up of https://github.com/envoyproxy/ai-gateway/pull/925

docs: use uncompressed json format

---

README.md

This PR updates README with llm inference pool highlight.

docs: update readme with details

---

examples/inference-pool/base.yaml
go.mod
go.sum
site/docs/capabilities/inference/aigatewayroute-inferencepool.md
site/docs/capabilities/inference/httproute-inferencepool.md
tests/e2e/e2e_test.go

feat: bump gateway api inference extension to v0.5.1

---

site/blog/2025/2025-07-15-envoy-ai-gateway-reference-architecture.md
site/docs/capabilities/index.md
site/docs/capabilities/llm-integrations/connect-providers.md
site/docs/capabilities/llm-integrations/index.md
site/docs/getting-started/connect-providers/index.md

Adding a page with information regarding how to connect to providers in general.
Adding links to the new page and updating info on the getting started guide.
n/a
Got feedback that it would be helpful to improve the docs around adding routing to providers

docs: adding Connecting to AI Providers Doc

---

README.md

This PR removed the extra `The` letter in README

docs: remove extra word in readme

---

examples/basic/basic.yaml
site/docs/getting-started/basic-usage.md

This adds an example usage of ClientTrafficPolicy which is every will have to configure most cases.
Closes #828

docs: document ClientTrafficPolicy should be configured

---

examples/inference-pool/config.yaml
site/docs/capabilities/inference/aigatewayroute-inferencepool.md
site/docs/capabilities/inference/httproute-inferencepool.md
tests/e2e/e2e_test.go

Fixes: https://github.com/envoyproxy/ai-gateway/issues/953
I am thinking if we should let users install inferencepool in default, so this problem can be solved as well.

fix: separate init inferencepool config

---

internal/controller/gateway.go
internal/controller/gateway_test.go
tests/controller/controller_test.go
tests/e2e/testdata/testupstream.yaml

controller: automatically clean up deprecated resources

---

internal/extproc/translator/openai_gcpanthropic_stream.go
internal/extproc/translator/openai_gcpanthropic_stream_test.go
internal/extproc/translator/openai_gcpanthropic_test.go
tests/extproc/testupstream_test.go
tests/internal/testenvironment/test_environment.go

adding tests and more robust support for streaming with thinking

feat: add more support for gcp anthropic thinking

---

cmd/aigw/run.go
cmd/aigw/translate.go
internal/controller/controller.go
internal/controller/gateway.go
internal/controller/gateway_test.go

This removes unused field from Gateway controller `udsPath`.

refactor: removes unused field from gateway ctrl

---

internal/extensionserver/post_translate_modify.go

controller: set allowModeOverride=true

---

cmd/aigw/ai-gateway-default-resources.yaml
cmd/aigw/testdata/translate_basic.in.yaml
cmd/aigw/testdata/translate_basic.out.yaml
examples/basic/azure_openai.yaml
examples/inference-pool/aigwroute.yaml
examples/provider_fallback/base.yaml
site/docs/capabilities/inference/aigatewayroute-inferencepool.md
site/docs/getting-started/connect-providers/aws-bedrock.md
site/docs/getting-started/connect-providers/azure-openai.md
site/docs/getting-started/connect-providers/openai.md
site/versioned_docs/version-0.2/capabilities/fallback.md

docs: removes deprecated use of targetRefs

---

site/docs/capabilities/llm-integrations/supported-endpoints.md

docs: adds documentation on prefix config

---

internal/apischema/openai/openai.go
internal/apischema/openai/openai_test.go

This PR is support EncodingFormat in embedding models
Fixes #1034

feat: support the encodingFormat in embedding models

---

tests/controller/controller_test.go

we should trigger a reconciler after bsps are observed by the secret controller.
Fixes #1025 
NONE

fix: test race condition in secret controller

---

cmd/aigw/README.md
cmd/aigw/testdata/ai-gateway-ollama-docker.yaml

This adds a default ClientTrafficPolicy to the docker compose quick start configuration.
**Related Issues/PRs**
Same as #1094
**Special notes for reviewers**
I ran this with the [OpenTelemetry quick start with Phoenix](https://github.com/envoyproxy/ai-gateway/tree/main/cmd/aigw#quick-start-with-opentelemetry)
Then I used [Goose](https://block.github.io/goose/) with qwen3 as the backend to make a request that far exceeds the default buffer:
```bash
goose run -t 'what are the most impactful recent pull requests to https://github.com/envoyproxy/ai-gateway?'
```
Here's the output
```
---
**Author:** [aabchoo](https://github.com/aabchoo)  
**Impact:**  
- Adds critical security functionality for AWS OIDC integration  
- Enables secure communication between Envoy AI Gateway and …
```

cli: add default buffer limit to aigw run quick start

---

tests/extproc/bench_test.go
tests/extproc/extproc_test.go
tests/extproc/real_providers_test.go
tests/extproc/testupstream_test.go
tests/extproc/vcr/vcr_test.go
tests/internal/testenvironment/test_environment.go

This scaffolds the initial benchmark setup for extproc for future optimizations.

test: enables easy benchmarking of extproc

---

site/src/components/HomepageFeatures/index.tsx

This PR updates main page with v0.3 release

docs: update release info for v0.3

---

site/src/components/LLMProviders/index.tsx

This PR updated vertex ai support

docs: update vertex ai support

---

examples/basic/gcp_vertex.yaml
site/docs/capabilities/llm-integrations/connect-providers.md
site/docs/capabilities/llm-integrations/supported-endpoints.md

doc: fix up gcp anthropic version and example doc

docs: fix up gcp anthropic doc

---

tests/extproc/real_providers_test.go
tests/extproc/testupstream_test.go

This commit adds additional test cases that involves tool calls and responses, which is a basic pattern in agent applications.

test: adds more tool call related test cases

---

site/docs/cli/installation.md

cli: update docs with the link to the Docker registry
Follow-up of: https://github.com/envoyproxy/ai-gateway/pull/1157
N/A

cli: update docs with the link to the Docker registry

---

internal/apischema/awsbedrock/awsbedrock.go

Fix additionalModelRequestFields json field name.
Fixes #1155

fix: correct additionalModelRequestFields

---

internal/apischema/openai/openai.go
internal/apischema/openai/openai_test.go
internal/extproc/translator/gemini_helper.go
internal/extproc/translator/gemini_helper_test.go
internal/tracing/openinference/openai/request_attrs_test.go
tests/internal/testopenai/chat_requests.go

The `json_object` should be { "type": "json_object"}  according to OpenAI's API.
The codes is similar to `ChatCompletionContentPartUserUnionParam`

fix: the response_format type to make it compatible with OpenAI API

---

site/docs/getting-started/index.md
site/versioned_docs/version-0.3/getting-started/index.md

docs: remove quickstart
Fixes #1207

docs: remove quickstart

---

internal/extensionserver/inferencepool.go

This PR increased timeout from 5s for inferencepool extproc, preventing timeout from LLM

feat: increase timeout for inferencepool extproc

---

tests/e2e-upgrade/upgrade_test.go

This is a follow up on #1248, and enables the skipped test case by using the old commit hash. We will pin it later to the next version which is v0.4.0..

test: enables cp upgrade test case

---

site/docs/concepts/architecture/control-plane.md
site/docs/concepts/architecture/data-plane.md

site: adds more rationales in arch pages

---

site/docs/concepts/architecture/control-plane.md
site/docs/concepts/architecture/data-plane.md

In concepts doc section: add correction of a couple grammar mistakes.  Add a link to k8s sidecar reference.
n/a
n/a

fix(site/docs): grammar fixes and k8s sidecar ref for concepts section

---

examples/mcp/agent.py

Fixes the MCP agent Python example. It was missing an import statement, and without i,t the agent traces were not properly generated.
Related: https://github.com/envoyproxy/ai-gateway/pull/1295
N/A

docs: fix mcp agent example
