envoyproxy/ai-gateway

- .golangci.yml
- Makefile
- Makefile.tools.mk
Randomly was reading through this repo and found this potential cleanup, feel free to reject if not needed
- `gofmt` and `gofumpt` fully overlap, so remove `gofmt` linter since `gofumpt` is more advanced
- `gci` and `goimports` fully overlap, so remove `goimports` linter since `gci` is more avanced.
- If wanting to use `goimports`, can do the reverse, but I don't recommend it since it formats much worse IMO
- Replace `goimports` with `gci` in Makefile to correspond to above change
- Removes `awk` hack since not needed for `gci`
- Should be reverted if picking `goimports` instead of `gci`, basically both Makefile and golangci.yml should define the same thing
A change that came to mind but was larger than the above was replacing manual invocation of `gofumpt` and `gci` in Makefile with …
> Remove duplicate linters and use gci for imports

- .github/workflows/docker_builds_template.yaml
Previously the containers were pushed regardless of whether
it is kicked by PRs or commits (push events).  This fixes that.
> ci: do not push containers on PRs

- extprocconfig/extprocconfig.go
- extprocconfig/extprocconfig_test.go
- go.mod
- internal/cmd/extproc/main.go
- internal/extproc/mocks_test.go
- internal/extproc/processor.go
- internal/extproc/processor_test.go
- internal/extproc/router/request_body.go
- internal/extproc/router/request_body_test.go
- internal/extproc/router/router.go
- internal/extproc/router/router_test.go
- internal/extproc/server.go
- internal/extproc/server_test.go
- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_awsbedrock_test.go
- internal/extproc/translator/openai_openai.go
- internal/extproc/translator/openai_openai_test.go
- internal/extproc/translator/translator.go
- internal/extproc/translator/translator_test.go
- internal/extproc/watcher.go
- internal/extproc/watcher_test.go
This scaffolds and implements the initial logic based on the 
current API. Notably, I intentionally organized the extproc code 
in a way that it is decoupled from EG concepts as well as the 
AI Gateway API level constructs. The rationale is that it not only
allows us to test the extproc without relying on not only EG/AIG
and even without kubernetes at all, but also some users are asking
for the use of outside the ai-gateway projects.
As for the implementation, there's nothing special going on, and 
it is simply mostly migrated from the MVP with the decoupling in mind.
I will follow up with the end-to-end test in subsequent PRs.
> extproc: initial implementation

- .github/workflows/safe_to_test.yaml
- .github/workflows/tests_using_secrets.yaml
- Makefile
- go.mod
- go.sum
- internal/apischema/openai/openai.go
- internal/extproc/mocks_test.go
- internal/extproc/processor.go
- internal/extproc/processor_test.go
- internal/extproc/router/request_body.go
- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_awsbedrock_test.go
- internal/extproc/translator/openai_openai.go
- internal/extproc/translator/openai_openai_test.go
- internal/extproc/translator/translator.go
- tests/extproc/envoy.yaml
- tests/extproc/extproc_test.go
This scaffolds the initial extproc e2e tests using the secrets.
The GHA workflow is defined in a separate file so that we can run
the tests for PRs coming from fork repos as well under the condition that
a maintainer verifies the code and adds the label "safe-to-test".
The actual test for AWS bedrock is commented out now as we will do the
request signing inside the extproc.
> Scaffolds the initial extproc e2e test 

- api/v1alpha1/api.go
- manifests/charts/ai-gateway-helm/crds/aigateway.envoyproxy.io_llmroutes.yaml
- tests/cel-validation/main_test.go
- tests/cel-validation/testdata/llmroutes/unsupported_match.yaml
This was a missing CEL validation in #47.
In the near future, we will support the regular
expression, but for now simply reject the 
configuration as documented in the comment.
> api: adds missing CEL validation on LLMRouteRuleMatch

- Makefile
- extprocconfig/extprocconfig.go
- extprocconfig/extprocconfig_test.go
- go.mod
- internal/extproc/mocks_test.go
- internal/extproc/processor.go
- internal/extproc/processor_test.go
- internal/extproc/server.go
- internal/extproc/server_test.go
- tests/extproc/envoy.yaml
- tests/extproc/extproc_test.go
This implements the only necessary logic to achieve 
the token-based rate limit in the external processing code.
The only thing it needs to do is to set the filter dynamic metadata
which contains the extracted used token.
The set number can be used to reduce the rate limit budget thanks
to the new feature introduced in the upstream Envoy to be released
with the next version 1.33. 
See 
* https://github.com/envoyproxy/envoy/pull/37548
* https://github.com/envoyproxy/envoy/pull/37684
* https://github.com/envoyproxy/ratelimit/pull/802
> extproc: sets token usage into filter metadata

- api/v1alpha1/api.go
- cmd/controller/main.go
- extprocconfig/extprocconfig.go
- extprocconfig/extprocconfig_test.go
- go.mod
- internal/controller/controller.go
- internal/controller/llmbackend.go
- internal/controller/llmbackend_test.go
- internal/controller/llmroute.go
- internal/controller/llmroute_test.go
- internal/controller/sink.go
- internal/controller/sink_test.go
- internal/extproc/processor.go
- internal/extproc/processor_test.go
- internal/extproc/server.go
- internal/extproc/server_test.go
- internal/extproc/watcher_test.go
- manifests/charts/ai-gateway-helm/crds/aigateway.envoyproxy.io_llmroutes.yaml
- tests/cel-validation/testdata/llmroutes/basic.yaml
- tests/cel-validation/testdata/llmroutes/non_openai_schema.yaml
- tests/cel-validation/testdata/llmroutes/unknown_schema.yaml
- tests/cel-validation/testdata/llmroutes/unsupported_match.yaml
- tests/extproc/extproc_test.go
This commit adds the initial implementation of the resource 
management controllers. As per the official recommendation of
controller-runtime, the controller interface is implemented per
CRD. Therefore, this adds two typical "controller" one for LLMRoute
and another for LLMBackend.
In addition, this implements "configuration sink" which is the sync
mechanism across multiple resource events via Go channel. It has
the global view over all AI Gateway resources and hence have the 
full context required to create a final extproc configuration as well
as HTTPRoute. The following is the (very) simple diagram for the
relationship among k8s events, controllers and configSink.
k8s events --async--> {llmRouteCtrl, llmBackendCtrl, ...} --sinkEvent (sync)--> configSink
The followup PR will add the end …
> Adds initial controller implementation 

- .github/workflows/trivy.yaml
Introduced Trivy image vulnerabilities scan workflow
- This workflow is triggered on merges to the main branch and runs once daily (schedule can be adjusted if needed).
- It currently scans both the controller and extproc images.
> Add trivy image scan workflow

- cmd/controller/main.go
- internal/controller/controller.go
- internal/controller/llmroute.go
- tests/controller/controller_test.go
- Fixing the issue that logr is not initialized 
- Better debugging reconciliation issue
2025-01-13T00:06:18Z    ERROR   Reconciler error        {"controller": "llmroute", "controllerGroup": 
"aigateway.envoyproxy.io", "controllerKind": "LLMRoute", "LLMRoute": {"name":"llmroute","namespace":"gateway"}, 
"namespace": "gateway", "name": "llmroute", "reconcileID": "7c2497ba-9252-44cc-b06e-dc4854b454f4", "error": 
"failed to update extension policy: EnvoyExtensionPolicy.gateway.envoyproxy.io \"ai-gateway-llm-route-extproc-
llmroute\" is invalid: spec: Invalid value: \"object\": either targetRef or targetRefs must be used"}
```
> Refactor controller args and logs

- cmd/extproc/main.go
- internal/controller/sink.go
- internal/controller/sink_test.go
Fix following error with backend output schema is missing in the extproc config map 
time=2025-01-13T02:47:27.826Z level=INFO msg="starting external processor" version=bcf33a98b8df4293493e5f213f9fd7a753b36073
time=2025-01-13T02:47:27.828Z level=INFO msg="loading a new config" path=/etc/ai-gateway/extproc/extproc-config.yaml
2025/01/13 02:47:27 failed to start config watcher: failed to load initial config: cannot create translator factory: unsupported API schema combination: client={OpenAI }, backend={ }
> Fix backend output schema in extproc configmap

- filterconfig/filterconfig.go
- filterconfig/filterconfig_test.go
- internal/controller/llmroute.go
- internal/controller/llmroute_test.go
- internal/controller/sink.go
- internal/controller/sink_test.go
- internal/extproc/backendauth/auth.go
- internal/extproc/backendauth/aws.go
- internal/extproc/mocks_test.go
- internal/extproc/processor.go
- internal/extproc/processor_test.go
- internal/extproc/router/request_body.go
- internal/extproc/router/request_body_test.go
- internal/extproc/router/router.go
- internal/extproc/router/router_test.go
- internal/extproc/server.go
- internal/extproc/server_test.go
- internal/extproc/translator/translator.go
- internal/extproc/translator/translator_test.go
- internal/extproc/watcher.go
- internal/extproc/watcher_test.go
- tests/extproc/extproc_test.go
Per #90, we will migrate to dynamic modules in the second or third version of
AI Gateway, the public configuration package must not be coupled with
extproc (see the description in the issue). This renames `extprocconfig`
to more generic (and accurate) name as `filterconfig`.
> Renames extprocconfig to filterconfig

- CONTRIBUTING.md
- Makefile
> Adds make help target

- internal/extproc/mocks_test.go
- internal/extproc/processor.go
- internal/extproc/router/router.go
- internal/extproc/router/router_test.go
To minimize the change needed to discuss #104
> extproc: refactors router code

- api/v1alpha1/api.go
- internal/controller/sink.go
- internal/controller/sink_test.go
- manifests/charts/ai-gateway-helm/crds/aigateway.envoyproxy.io_aiservicebackends.yaml
- tests/controller/controller_test.go
Previously, ` egv1a1.BackendRef` was used for referencing 
backends from AIServiceBacked. However, that's unnecessary
indirection from `gwapiv1.BackendObjectReference` because
the former is basically a wrapper of the latter with unused field.
Basically this removes the unnecessary field from the CRD and 
therefore simplifies the implementation.
> api: Use gwapiv1.BackendObjectReference instread of unstable EG one

- api/v1alpha1/api.go
- manifests/charts/ai-gateway-helm/crds/aigateway.envoyproxy.io_aigatewayroutes.yaml
- tests/cel-validation/main_test.go
- tests/cel-validation/testdata/aigatewayroutes/basic.yaml
- tests/cel-validation/testdata/aigatewayroutes/no_target_refs.yaml
- tests/cel-validation/testdata/aigatewayroutes/unknown_schema.yaml
- tests/cel-validation/testdata/aigatewayroutes/unsupported_match.yaml
Previously targetRefs can be empty. However, in reality,
such AIGatewayRoute is useless while making it necessary
for controller to handle the edge case. This sets the CEL
validation rule to require at least one TargeRefs to exist.
> api: adds cel validation on requiring at least one targetRefs

- Makefile
Fixes the multi-platform Docker build (see as an example [this build](https://github.com/envoyproxy/ai-gateway/actions/runs/12820298883/job/35749679784) only building for the current arch/platform). The main issue was that inside the docker target, the `PLATFORMS` and `GOARCH_LIST` variables were set as shell variables (at target execution time), but they were expected to be Makefile variables (target definition time) by the docker target.
This PR fixes it by properly defining the values as target-scoped variables, to avoid them interfering in other targets).
Before:
```
$  make docker-build.extproc ENABLE_MULTI_PLATFORMS=true TAG=$TAG DOCKER_BUILD_ARGS="--push"
-> Building extproc for linux/amd64
<- Built out/extproc-linux-amd64
make[1]: Leaving directory …
```
> build: fixes multi-platform docker build

- RELEASES.md
- SUPPORT_POLICY.md
This commit adds RELEASES.md documentation
that describes the release cycles and the support
policy especially around the compatibility promises.
fixes #21
> docs: adds RELEASES.md

- .github/workflows/commit.yaml
- .github/workflows/docker_builds_template.yaml
- .yamllint
- Makefile
- Makefile.tools.mk
- tests/cel-validation/testdata/aigatewayroutes/basic.yaml
- tests/cel-validation/testdata/aigatewayroutes/no_target_refs.yaml
- tests/cel-validation/testdata/aigatewayroutes/non_openai_schema.yaml
- tests/cel-validation/testdata/aigatewayroutes/unknown_schema.yaml
- tests/cel-validation/testdata/aigatewayroutes/unsupported_match.yaml
> chore: enable yamllint check

- filterconfig/filterconfig.go
The YAML library being used does not honor the `yaml` tags. It just considers the `json` ones and the extproc filter config was not unmarshaleld according to the defined values.
The `llmRequestCosts.metadataKey` and `MetadataNamespace` properties had wrong tags.
> extproc: fix filter config marshalling

- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_awsbedrock_test.go
This is a follow-up PR for: https://github.com/envoyproxy/ai-gateway/pull/117#issuecomment-2598396168
I think it makes sense to do the same conversions and set it as "system"? The "developer" role is a replacement for "system" in OpenAI, so it should be fine?
> translator: support the developer role in Bedrock translator

- cmd/extproc/mainlib/main.go
- cmd/extproc/mainlib/main_test.go
Allows configuring extproc to listen on an Unix domain socket. Note that this PR just enables it in the extproc filter. Follow-up PRs will be needed to accommodate that in the controller as well, but that would require further changes to how the Gateway itself (not only the filter) is deployed, to mount a common volume for the UDS.
> extproc: allow configuring an UDS listen address

- internal/controller/sink.go
- internal/controller/sink_test.go
- tests/controller/controller_test.go
- tests/e2e/testdata/translation_testupstream.yaml
- tests/e2e/translation_testupstream_test.go
- tests/envtest.go
- tests/testupstream/main.go
> feat: sets the host automatically to Backend 

- internal/extproc/backendauth/api_key.go
- internal/extproc/backendauth/api_key_test.go
- internal/extproc/backendauth/auth.go
Previously, the API was read on the request path,
which is left to be fixed and left as TODO in #125.
This fixes it and makes extproc load the APIKey
at the config load time.
Follow up on #125
> extproc: load APIKey on load time

- examples/token_ratelimit/README.md
- examples/token_ratelimit/token_ratelimit.yaml
- internal/extproc/processor.go
- internal/extproc/processor_test.go
- tests/e2e/e2e_test.go
- tests/e2e/init/envoygateway/config.yaml
- tests/e2e/init/ratelimit/radis.yaml
- tests/e2e/init/ratelimit/redis.yaml
- tests/e2e/token_ratelimit_test.go
- tests/e2e/translation_testupstream_test.go
This adds the example that demonstrates how to use
token based rate limit per unique user-id. Basically,
this utilizes the latest Envoy Gateway's request
cost features.
> examples: adds token rate limit

- tests/e2e/e2e_test.go
This fixes the flake during waiting for ratelimit server
is up in the end-to-end test.
This is a follow up on #171
> test: fixes flake during waiting for ratelimit server

- tests/e2e/basic_test.go
- tests/e2e/token_ratelimit_test.go
- tests/e2e/translation_testupstream_test.go
This fixes or mitigates a flake of examples/basic
end to end test by re-creating the connection inside
the require-eventually-loop.
> test: fixes flake of examples/basic e2e

- .github/dependabot.yml
This fixes the placement of `ignore` section
in dependabot.yml.
Follow up on #174
> ci: fixes dependabot.yml

- cmd/extproc/mainlib/main.go
- internal/controller/sink.go
- tests/extproc/custom_extproc_test.go
- tests/extproc/extproc_test.go
- tests/extproc/real_providers_test.go
- tests/extproc/testupstream_test.go
Previously, filterconfig package was named extprocconfig
and renamed to it in #92. This fixes a few places still 
mentioning the old name.
follow up on #92
> chore: updates the old package names

- .github/workflows/docker_builds_template.yaml
- examples/basic/basic.yaml
- tests/e2e/basic_test.go
- tests/internal/testupstreamlib/testupstream/main.go
- tests/internal/testupstreamlib/testupstream/main_test.go
As a part of documentation, we need a fake upstream server
that returns openai responses but without credentials.
This modifies the testupstream so that it can return the 
fake openai response when the response body is not given
by the client and the path is known.
To make the testupstream usable in the doctest, this will
start pushing the testupstream to GHCR.
> test: testupstream returns openai fake responses

- .gitignore
- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
- internal/controller/controller.go
- internal/controller/sink.go
- tests/controller/controller_test.go
Fixes #134
This PR makes the AIGatewayRoute controller to watch the resources that are created by it and trigger reconcilation.
> controller: fix watch resources that are created by the controller

- internal/extproc/watcher.go
- internal/extproc/watcher_test.go
feat: print diff on config change
When the configuration file is updated, the logger will print the
updated sections at the DEBUG level. The implementation is
straightforward and does not rely on any external libraries, making it
particularly useful for troubleshooting.
Output:
```
time=2025-01-28T11:46:03.911+01:00 level=INFO msg="loading a new config" path=docs/extproc-config.yaml
time=2025-01-28T11:46:03.911+01:00 level=DEBUG msg="config line changed" line=14 path=docs/extproc-config.yaml old="weight: 1" new="weight: 0"
```
Signed-off-by: Sébastien Han <seb@redhat.com>
**Special notes for reviewers (if applicable)**:
> feat: print diff on config change

- site/docs/index.md
- site/docs/intro.md
- site/docusaurus.config.ts
I changed the overview.md to be the home/index of the docs site.
I moved the Docs link to the right side of the navigation bar.
Please add the related issues or PRs here.
Related: #29
> docs: Moved docs link, and changed Overview to Home of Docs site

- filterconfig/filterconfig.go
- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
- internal/controller/ai_service_backend.go
- internal/controller/controller.go
- internal/controller/controller_test.go
- internal/controller/secret.go
- internal/controller/secret_test.go
- internal/controller/sink.go
- internal/controller/sink_test.go
- internal/extproc/backendauth/aws.go
- tests/controller/controller_test.go
This adds a secret watcher controller that enables the 
hot reload of any secret referenced by backendTrafficPolicy.
Follow up on #43  #106 #161 
Supersede #185
> controller: adds secret watcher to trigger extproc config updates

- internal/controller/sink.go
- internal/controller/sink_test.go
- internal/extproc/processor.go
- internal/extproc/server.go
- internal/extproc/server_test.go
- tests/e2e/basic_test.go
Without triggering pods into the reconcile loop of k8s server,
the config map updates will take a few minutes to be picked up
and reflected on the actual file of the pod [^1].
This commit changes the config sink so that it will add the config
uuid to the extproc pods annotations.
[^1]: https://neonmirrors.net/post/2022-12/reducing-pod-volume-update-times/
Follow up on #219
> controller: annotate extproc pods with uuid for faster refresh

- cmd/controller/main.go
- internal/controller/ai_gateway_route.go
- internal/controller/ai_service_backend.go
- internal/controller/controller.go
- internal/controller/sink.go
Previously, all loggers used by controllers are name-prefixed with "setup"
which is not correct and confusing, so this fixes it. Also, this consolidates
all the WithName option handling in StartController function so that we can
ensure all controllers have consistent names.
> controller: consistent logger prefix for controllers

- site/docs/getting-started/connect-providers/aws-bedrock.md
- site/docs/getting-started/connect-providers/openai.md
This was necessary before #219 and #224 landed
the main branch. Now the secret updates will be 
automatically picked up by the extproc without restarts.
This behavior is already being tested in an e2e test.
> docs: removes the instruction to restart extproc

- .github/workflows/style.yaml
- .github/workflows/tests.yaml
This moves the style checks from the test jobs,
so that we can set the paths-ignores on these
test targets while always running style check
regardless of the changed files.
> ci: separates out style checks from tests

- site/docs/getting-started/connect-providers/index.md
- site/docs/getting-started/connect-providers/openai.md
Block should be indented.
Some unrelated minor Markdown formatting improvements like using auto-incrementing lists and removing unnecessary colons.
> docs: fix code block indentation

- internal/extproc/server.go
- internal/extproc/server_test.go
This commit introduces functions to redact sensitive headers and body content before logging, ensuring that sensitive information such as authorization tokens is not exposed in debug logs. The new filterSensitiveHeaders function redacts specified headers, replacing their values with [REDACTED], while filterSensitiveBody ensures that sensitive content in request bodies is also redacted before being logged.
Additionally, the logging behavior has been updated so that request headers and body content are only logged when the DEBUG level is enabled, further improving security and performance.
Unit tests have been added to verify the functionality of both filterSensitiveHeaders and filterSensitiveBody, ensuring that sensitive data is properly redacted and that the logging …
> feat: redact sensitive headers and body content in debug logs

- examples/extproc_custom_router/main.go
- filterapi/filterconfig.go
- filterapi/filterconfig_test.go
- filterapi/x/x.go
- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
- internal/controller/sink.go
- internal/controller/sink_test.go
- internal/extproc/backendauth/api_key.go
- internal/extproc/backendauth/api_key_test.go
- internal/extproc/backendauth/auth.go
- internal/extproc/backendauth/aws.go
- internal/extproc/backendauth/aws_test.go
- internal/extproc/mocks_test.go
- internal/extproc/processor.go
- internal/extproc/processor_test.go
- internal/extproc/router/request_body.go
- internal/extproc/router/request_body_test.go
- internal/extproc/router/router.go
- internal/extproc/router/router_test.go
- internal/extproc/server.go
- internal/extproc/server_test.go
- internal/extproc/translator/translator.go
- internal/extproc/translator/translator_test.go
- internal/extproc/watcher.go
- internal/extproc/watcher_test.go
- tests/extproc/custom_extproc_test.go
- tests/extproc/extproc_test.go
- tests/extproc/real_providers_test.go
- tests/extproc/testupstream_test.go
This does the two re-organization of packages:
* Renames `filterconfig` to `filterapi` 
* Put `extprocapi` into `filterapi/x` package 
The `filterapi/x` package will serve as an experimental
package that facilitates the development of such features.
Notably, custom routers etc while keeping the ability to
introduce breaking changes at any release. This will be 
for advanced users as well as core contributors to iterate
on some advanced features in the single repo.
For #233
> chore: reorganizes custom router/filterapi package

- cmd/controller/main.go
- cmd/controller/main_test.go
- go.mod
- internal/controller/controller.go
- internal/controller/sink.go
- internal/controller/sink_test.go
- manifests/charts/ai-gateway-helm/templates/deployment.yaml
- manifests/charts/ai-gateway-helm/values.yaml
This refactors the main function of controller.
Previously it was conflated with the implementation detail
(zap) and that is exposed unnecessarily as controller main
arguments. This resolves it and expose the only necessary
one to have the consistency with extproc.
Notably, this also adds an new controller argument/helm 
value that configures the log level of external processor.
More fine tuned, per-route log level can be added later 
as in #204.
This also increases the test coverage.
Supersedes #204
> controller: refactors flags

- cmd/controller/main.go
- cmd/controller/main_test.go
- cmd/extproc/mainlib/main.go
- cmd/extproc/mainlib/main_test.go
- examples/extproc_custom_router/README.md
This is a follow up on #235  and does the same
refactoring to external processor.
> extproc: refactors flags and adds test

- CODE_OF_CONDUCT.md
This was copied from Envoy Gateway as-is
and should be "Envoy AI Gateawy" instead of
Envoy Gateway.
> docs: fixes CODE_OF_CONDUCT.md

- .github/workflows/tests.yaml
- .testcoverage.yml
- Makefile
- Makefile.tools.mk
- filterapi/filterconfig_test.go
- internal/extensionserver/extension_server_test.go
- internal/extproc/backendauth/auth_test.go
- internal/extproc/processor_test.go
- internal/extproc/translator/openai_awsbedrock_test.go
- internal/extproc/translator/openai_openai.go
- internal/extproc/translator/translator.go
- internal/llmcostcel/cel.go
- internal/llmcostcel/cel_test.go
- tests/internal/testupstreamlib/testupstream/main.go
- tests/internal/testupstreamlib/testupstream/main_test.go
This introduces the unit test coverage checks
in GHA. Note that this doesn't utilize the integration
tests (test-extproc,test-controller and test-e2e), so
the coverage will be checked solely on the unit tests
without relying on the external binaries etc.
One left TODO is to remove the exclusion of controller
package which requires a bit of refactoring, so i will
follow up in a separate PR.
> test: adds unit test coverage checks 

- .github/workflows/style.yaml
- .github/workflows/tests.yaml
This upgrades the Envoy Gateway version used 
in the end to end tests. Also, this changes the 
Envoy container tag to use "-latest" without
specifying the patch version.
> ci: upgrades Envoy Gateway to v1.3.0

- site/docs/getting-started/installation.md
**Commit Message**: 
Removal of deprecated kubectl command below from [the installation getting started guide](https://github.com/envoyproxy/ai-gateway/blob/main/site/docs/getting-started/installation.md).
`kubectl wait --timeout=2m -n envoy-ai-gateway-system deployment/ai-gateway-controller --for=create
`
It seems to include a deprecated arg ```--for=create```
**Related Issues/PRs (if applicable)**: Fixes [Issue 262](https://github.com/envoyproxy/ai-gateway/issues/262)
**Special notes for reviewers (if applicable)**:
> docs: removal of deprecated kubectl command in installation.md

- .github/workflows/pr_style_check.yaml
This follows up on #266 and relaxes the PR title length 
restriction to 60 characters. It was too strict.
> ci: relaxes PR title length check

- tests/extproc/envoy.yaml
Addressed warnings observed during `make test-extproc`, except for the `reuse_port` warning, which is platform-dependent and cannot be fixed on non-Linux systems.
- Updated `json_format` to be nested under `log_format` to align with Envoy's expected configuration.
- Added `overload_manager` configuration to manage downstream connection limits.
- The warning related to `reuse_port` being force disabled on non-Linux platforms was **not** fixed, as it is platform-dependent.
Signed-off-by: Sébastien Han <seb@redhat.com>
#274
The warning related to `reuse_port` being force disabled on non-Linux platforms was **not** fixed, as it is platform-dependent. Any suggestions for a fix are welcome.
> test: resolve warnings in envoy.yaml

- .github/workflows/issue_title_check.yaml
This introduces a new GitHub Actions workflow to check the length of issue titles and provide feedback if they exceed a specified limit. 
Fixes https://github.com/envoyproxy/ai-gateway/issues/270
`.github/workflows/issue_title_check.yaml`: Created a new workflow named "Issue Title Check" that triggers on issue creation and edits. It includes two jobs: `check_title_length` to validate the title length and `comment_if_long` to leave a comment if the title is too long.
I checked the behavior with the forked repository.
> ci: add issue title check

- tests/extproc/real_providers_test.go
This cleans up some logic for old Envoy versions in
log parsing. Also, this adds additional test log
for debugging a flaky streaming test with openai.
Related to #290
> test: clean up real provider extproc test

- examples/token_ratelimit/token_ratelimit.yaml
- tests/e2e/token_ratelimit_test.go
The weight field does not need to be specified if there's only 
one backend since #156. This removes it in token_ratelimit.yaml.
Follow up on #289
> examples: simplifies token_ratelimit.yaml

- internal/extproc/backendauth/api_key.go
- internal/extproc/backendauth/api_key_test.go
- internal/extproc/backendauth/auth.go
- internal/extproc/backendauth/aws.go
- internal/extproc/backendauth/aws_test.go
- internal/extproc/processor.go
This refactors the extproc package and 
eliminates all context.Background usages.
> extproc: eliminates context.Background

- filterapi/filterconfig_test.go
- internal/extproc/backendauth/auth.go
- internal/extproc/backendauth/auth_test.go
- internal/extproc/backendauth/aws.go
- internal/extproc/backendauth/aws_test.go
- internal/extproc/server.go
- internal/extproc/server_test.go
- internal/extproc/watcher.go
- internal/extproc/watcher_test.go
This eliminates context.Background in config loading 
code path.
This is a follow up on #296
> extproc: eliminates context.Background in config loader

- .golangci.yml
- internal/apischema/awsbedrock/awsbedrock.go
- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
- internal/controller/ai_service_backend_test.go
- internal/controller/controller_test.go
- internal/controller/sink.go
- internal/controller/sink_test.go
- internal/extproc/mocks_test.go
- internal/extproc/router/request_body.go
- internal/extproc/router/router_test.go
- internal/extproc/server.go
- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_awsbedrock_test.go
- internal/extproc/translator/openai_openai.go
- internal/extproc/watcher.go
- internal/llmcostcel/cel.go
- tests/controller/controller_test.go
- tests/internal/envtest.go
- tests/internal/testupstreamlib/testupstream/main.go
- tests/internal/testupstreamlib/testupstream/main_test.go
This makes the lint settings stricter and
starts enforcing more rules.
> chore: stricter golangci-lint

- tests/extproc/real_providers_test.go
Allow setting AWS session token in the AWS credential file when using AWS temporary credentials to test AWS Bedrock.
TEST_AWS_SESSION_TOKEN is optional if using static AWS credential.
> e2e: support AWS Session Token in real provider test

- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_openai.go
The extproc bahavior has changed since envoyproxy/envoy#38254
which is not released yet. This adds a TODO comment for the 
future iteration after it is released.
> extproc: add TODO comment on ProcessingMode

- Makefile.tools.mk
Previously, all Go-installed tools are always installed because of the trailing spaces. This fixes Makefile.tools.mk so that we can properly cache the tools.
Fixes #320
> chore: fix always reinstall

- tests/e2e/basic_test.go
- tests/e2e/e2e_test.go
- tests/extproc/real_providers_test.go
This modifies the e2e of basic usage example where some cases use credentials. Previously, if any one of them is missing, the entire test was skipped. This makes each credential optional and allows to partially run available test cases.
This is a counterpart of #326  in tests/e2e
> e2e: makes each credential optional

- Makefile
- Makefile.tools.mk
- tests/e2e/e2e_test.go
> chore: add helm install

- internal/controller/ai_gateway_route.go
- tests/controller/controller_test.go
This removes the unnecessary code path of settings object kinds during the reconciliation of AIGatewayRoute. Previously, it existed only because there was a check in tests/controller.
> controller: removes unnecessary gvks setter

- .github/workflows/pr_style_check.yaml
- manifests/envoy-gateway-config/redis.yaml
- site/docs/getting-started/installation.md
- tests/e2e/e2e_test.go
Previously, redis was not part of manifests/envoy-gateway/config and only deployed during e2e tests, not mentioned in the documentation site. However, the Envoy Gateway config assumes the existence of redis deployment hence users followed the tutorial might have observed the crashing deployment of rate-limit-service. In addition, we now have a rate limit doc[1], so the deployment of the redis must be a part of the set up.
1: https://envoy-ai-gateway.netlify.app/docs/capabilities/usage-based-ratelimiting
> chore: moves redis.yaml to manifests/envoy-gateway-config

- CONTRIBUTING.md
Since #323, helm is no longer needed to be locally installed.
> docs: helm is no longer required in CONTRIBUTING.md

- .gitignore
- tests/extproc/envoy.yaml
This will be helpful in debugging connectivity especially. Now you can spawn `envoy -c ./tests/extproc/envoy.yaml` and open `localhost:9901` on your browser to debug the connectivity.
> e2e: adds admin interface in extproc test

- CONTRIBUTING.md
extproc integration test requires a certain ca-certificate to be visible to envoy.
> docs: comment about ca-certificates in CONTRIBUTING

- manifests/charts/ai-gateway-helm/Chart.yaml
Now that the website is hosted at aigateway.envoyproxy.io, this references the URL in our helm chart.
> chore: reference aigateway.envoyproxy.io in helm

- internal/extproc/chatcompletion_processor.go
- internal/extproc/mocks_test.go
- internal/extproc/models_processor.go
- internal/extproc/processor.go
- internal/extproc/server.go
- internal/extproc/server_test.go
This removes the unnecessary suffix "Iface" from extproc.ProcessorIface interface. 
Follow up on  #325
> extproc: removes Iface suffix from processor

- site/docs/getting-started/basic-usage.md
- tests/internal/testupstreamlib/testupstream/main.go
docs: use correct JSON key names in basic-usage.md for the example chat completion.
Also make the `testupstream` server return a `.choices[].message.role` field to
be consistent with docs.
> docs: use correct JSON key names in basic-usage.md

- site/docs/getting-started/connect-providers/aws-bedrock.md
to link to next page for "Connect Local Model"
instead of linking to previous page "Connect OpenAI."
> docs: update AWS Bedrock next steps

- manifests/charts/ai-gateway-helm/Chart.yaml
This fixes the maintainers url in our helm chart which previously incorrectly pointed to EG.
> docs: fixes maintainers url in Chart.yaml

- .gitignore
- tests/e2e/e2e_test.go
e2e: collect kind logs on failure and destroy cluster
When e2e tests succeed, destroy the kind cluster. When e2e tests fail, keep the kind cluster up & running for troubleshooting, and collect the logs to the `tests/e2e/logs` directory to facilitate log analysis.
These logs are also uploaded as CI artifacts when e2e fail, to help troubleshoot why e2e tests could have failed on CI.
N/A
N/A
> e2e: collect kind logs on failure and destroy cluster

- .licenserc.yaml
- CONTRIBUTING.md
- pre-commit.sh
that runs `make precommit`.
closes #368
> ci: instruct how to set up git pre-commit hook

- Makefile
I think the target should be `test-crdcel` because `test-cel` doesn't exist.
> docs: fix incorrect make target in help message

- filterapi/filterconfig.go
- filterapi/filterconfig_test.go
- internal/extproc/watcher.go
- internal/extproc/watcher_test.go
extproc: load default config if file does not exist
If the configuration file does not exist, let extproc run with the default configuration. This prevents the extproc process from terminating if the config does not exist, which is a valid use case when the extproc filter is used in conjunction with other control planes.
N/A
N/A
> extproc: load default config if file does not exist

- internal/extproc/server.go
- internal/extproc/server_test.go
When debug level enabled, extproc logs the headers on request paths, and it reduces the sensitive value, especially authorization header values as a security measure. However, previously it modifies the original object accidentally hence it had caused a hard-to-debug unexpected behavior. This fixes the bug and ensures that the reduction is not applied to the original objects.
Thanks for the report by Bloomberg team @yuzisun 
Fixes a bug in #217
> extproc: do not modify original headers when debug enabled

- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
Previously, the deployment config is populated with the values specified in the AIGatewayRoute resource and not removed if the values is not specified. For example, after a replica value is specified, if a user removes it from AIGatewayFilterConfig, then the replica is not reverted to a default value. This fixes applyExtProcDeploymentConfigUpdate so that it will remove the previously specified value.
Thanks for pointing out @sanposhiho !
> controller: fixes extproc config update on removal

- .gitignore
- Makefile
chore: local default settings file
Allows having a local `.makerc` file with the custom values for the make variables.
N/A
N/A
> chore: local default settings file

- site/docs/capabilities/usage-based-ratelimiting.md
- site/docs/getting-started/basic-usage.md
- site/docs/getting-started/connect-providers/aws-bedrock.md
- site/docs/getting-started/connect-providers/openai.md
At the first iteration of the "getting started guide", I added `--fail` in all commands as we had an automated testing of the site documentation and it allowed us to detect if the curl command not is working. However, now we don't have any tests like that + `--fail` prevents users from seeing the actual error response from the upstream which makes it difficult to troubleshoot since it suppresses the response body due to the early cancel of requests. 
The root cause of #379 #375
> docs: removes --fail flags

- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- RELEASES.md
This set ups the release GHA workflow for the initial release!
> ci: adds release workflow

- site/docs/getting-started/connect-providers/aws-bedrock.md
docs: add note on enabling model access in the Connect AWS Bedrock page for the Llama 3.2 1B Instruct model in the `us-east-1` region specifically.
Otherwise, user will get this error.
```console
$ curl --silent \
-H "Content-Type: application/json" \
-d '{
"model": "us.meta.llama3-2-1b-instruct-v1:0",
"messages": [
{
"role": "user",
"content": "Hi."
}
]
}' \
$GATEWAY_URL/v1/chat/completions | jq .
{
"type": "error",
"error": {
"type": "AccessDeniedException:http://internal.amazon.com/coral/com.amazon.bedrock/",
"code": "403",
"message": "You don't have access to the model with the specified model ID."
}
}
```
> docs: add note on enabling model access

- internal/extproc/chatcompletion_processor.go
- internal/extproc/chatcompletion_processor_test.go
- internal/extproc/router/router.go
extproc: return HTTP 404 when no matching route
in `AIGatewayRoute` instead of a 500 status code.
```console
$ curl \
-H "Content-Type: application/json" \
-d '{
"model": "DEADBEEF",
"messages": [
{
"role": "user",
"content": "Who should be king of the world? Be direct, decisive, and opinionated."
}
]
}' $GATEWAY_URL/v1/chat/completions -i
HTTP/1.1 500 Not Found
content-length: 22
content-type: text/plain
date: Fri, 21 Feb 2025 12:51:06 GMT
```
```console
$ curl \
-H "Content-Type: application/json" \
-d '{
"model": "DEADBEEF",
"messages": [
{
"role": "user",
"content": "Who should be king of the world? Be direct, decisive, and opinionated."
}
]
}' $GATEWAY_URL/v1/chat/completions -i
HTTP/1.1 404 Not Found
content-length: 22
content-type: text/plain
date: Fri, 21 Feb …
```
> extproc: return HTTP 404 when no matching route

- internal/extproc/watcher_test.go
There was a race condition in extproc package's TestStartConfigWatcher test.
Follow up on #392
> test: fixes race in TestStartConfigWatcher

- Makefile
- manifests/charts/ai-gateway-helm/Chart.yaml
- manifests/charts/ai-gateway-helm/values.yaml
Previously, the container tags were pined to "latest" despite the version of helm chart being set to a release tag. This fixes it and adds a test.
> build: pin container tags to the release tag

- filterapi/x/x.go
- internal/extproc/chatcompletion_processor.go
- internal/extproc/chatcompletion_processor_test.go
- internal/extproc/router/router.go
extproc: make the route not found error public
This moves the route not found error to the `x` package together with the router interfaces so that custom implementations of the routing function can import and return it.
Follow-up for the post-merge comment in https://github.com/envoyproxy/ai-gateway/pull/399
N/A
> extproc: make the route not found error public

- internal/extproc/router/router.go
- internal/extproc/router/router_test.go
Right now if there are multiple, unweighted `backendRefs` in a [AIGatewayRouteRule], the first one is always returned. The correct behavior is to return a random one since they're essentially all weighted the same.
[AIGatewayRouteRule]: https://envoy-ai-gateway.netlify.app/docs/api/#aigatewayrouterule
contributes to #53
> extproc: pick random backend when multiple unweighted ones

- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_awsbedrock_test.go
- tests/extproc/testupstream_test.go
This fixes the OpenAI chat completion response choices conversion, there could only be one choice as AWS Bedrock does not support N choices. The previous code translated multiple content blocks to multiple choices which was wrong and for converse response there could be only one text block, however there can be multiple content blocks for text and toolUse.
Fixes #405 
Tested with the real AWS Bedrock with converse response including both text and toolUse content blocks.
This is an example of converse response and the previous code made wrong assumption that it is in the same content block:
```json
{
"message": {
"role": "assistant",
"content": [
{
"text": "To get the weather …
```
> extproc: fix openai response choice conversion for tool use

- .github/workflows/docker_builds_template.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- .github/workflows/trivy.yaml
- Makefile
- cmd/controller/main.go
- cmd/controller/main_test.go
- examples/basic/basic.yaml
- manifests/charts/ai-gateway-helm/values.yaml
- site/docs/getting-started/index.md
- site/docs/getting-started/installation.md
- tests/e2e/e2e_test.go
- tests/e2e/init/testupstream/manifest.yaml
This will switch to Docker Hub from GHCR for analytics purpose. Envoy organization is sponsored by Docker and it provides useful features that are not available with GHCR. The workflow is already verified to work. After this commit, our images will be published at
* https://hub.docker.com/r/envoyproxy/ai-gateway-helm
* https://hub.docker.com/r/envoyproxy/ai-gateway-controller
* https://hub.docker.com/r/envoyproxy/ai-gateway-extproc
* https://hub.docker.com/r/envoyproxy/ai-gateway-testupstream
> ci: migrate to docker.io from ghcr

- Makefile
- manifests/charts/ai-gateway-helm/Chart.yaml
This fixes the latest chart's image tag which previously was set to v0.0.0-latest. This fixes the helm-package recipe and now it points to :latest.
Follow up on #395
> ci: fixes packaged chart images on main branch

- internal/controller/oauth/client_credentials_token_provider.go
- internal/controller/oauth/client_credentials_token_provider_test.go
- internal/controller/oauth/oidc_provider.go
- internal/controller/oauth/oidc_provider_test.go
Set OIDC as a pointer in both OIDC Provider and ClientCredentialsTokenProvider's field. Updates occurring to OIDCProvider's oidcConfig will be "shared" with ClientCredentialsTokenProvider (cctProvider).
**Issue**
oidcProvider and cctProvider share the same oidc values on init (oidcProvider creates cctProvider and passes as param the same oidc value). The issue occurs in `FetchToken` as `token_endpoint` of oidc gets updated in oidcProvider and the subsequent call to cctProvider's `FetchToken` expects `token_endpoint` to be propagated. The value of `token_endpoint` in cctProvider is nil as no value is set to it.
Without propagating the value over, the error that shows up is: `failed to get token: fail to get oauth2 token Post "token_endpoint": unsupported protocol scheme …
> feat: store oidc as pointer for token providers

- internal/extproc/router/router.go
- internal/extproc/router/router_test.go
Previously, router instance shared the rng among multiple goroutines which is not a thread safe. This fixes it by having a goroutine local RNG. 
Contributes to #53
> extproc: fixes race condition with RNG

- .codespell.skip
This makes codespell ignore the log directory of e2e test.
follow up on #359
> chore: ignore test debug log dir from codespell

- internal/extproc/processor.go
- internal/extproc/processor_test.go
- internal/extproc/server.go
- internal/extproc/server_test.go
This fixes the edge case of extproc where response header processing phase is called with request header processing being skipped. That happens when an earlier filter sends some immediate response before it even reaches the AI Gateway filter. 
Closes #403
> extproc: properly handle early response

- internal/extproc/chatcompletion_processor.go
- internal/extproc/mocks_test.go
- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_awsbedrock_test.go
- internal/extproc/translator/openai_openai.go
- internal/extproc/translator/openai_openai_test.go
- internal/extproc/translator/translator.go
After #325, the translator is not where the abstraction over :path is implemented, but it moved to the choice of processor. As a result, the translator interface has become effectively tied to a specific endpoint, notably /v1/chat/completion. This renames the `translator.Translator` interface accordingly not only to remove the unnecessary code path but also facilitates the implementation of additional features like metrics. 
Follow up on #325 and contribute to #316
> extproc: renames translator interface

- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
- internal/controller/ai_service_backend_test.go
- internal/controller/backend_security_policy_test.go
- internal/controller/controller.go
- internal/controller/controller_test.go
- tests/internal/envtest.go
This refactors controller.go. Notably, this removes the unnecessary MustInitializeScheme and just expose the initialized schema and use it in test as well.
> controller: refactors controller.go

- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
- tests/controller/controller_test.go
This adds a code comment on why each translated HTTPRoute has a default route / on the first backend. This was brought up in the conversation in #384 and it is definitely worth a code comment on why it exists.
> controller: adds comments on default / rule

- .github/workflows/pr_style_check.yaml
This allows `backport` to be used as a commit title / PR title prefix.
Related to #437
> chore: allows backport prefix in commit title

- .github/workflows/pr_style_check.yaml
- internal/apischema/awsbedrock/awsbedrock.go
- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_awsbedrock_test.go
- tests/extproc/real_providers_test.go
* adding e2e test making sure that we can use a tool and return the proper response from the LLM
This PR also contains a few fixes that allow this test to work 
* added validateToolCallID as its needed for the bedrock message or it fails
* Validate and cast the openai content value into bedrock content block
- before we assumed it was always a string but it can also be an array
* Merge the content blocks if one has text and the other has toolcall but no text - bedrockResp.Output.Message.Content is not 1:1 with openai choice.Message.Content.. we get the result in chunks that should be merged, for example the text and it's toolconfig were in seperate elements but openai expects them to be in the same
* in openAIMessageToBedrockMessageRoleAssistant we assume that either …
> backport: e2e: add agent test using tool (#426)

- cmd/aigw/testdata/translate_basic.out.yaml
- cmd/aigw/translate.go
- cmd/aigw/translate_test.go
This adds a translation logic for HTTPRouteFilter resource that was missing from the initial implementation of `aieg translate` command.
Follow up on #439
> cli: adds translation for HTTPRouteFilter

- internal/controller/backend_security_policy.go
- internal/controller/backend_security_policy_test.go
- internal/controller/rotators/aws_oidc_rotator.go
- internal/controller/rotators/aws_oidc_rotator_test.go
- internal/controller/rotators/common.go
Update `Rotate` to return the expiration time in addition to the error. This will allow us to get the expiration time without having to make a `GET` API request to Kubernetes.
https://github.com/envoyproxy/ai-gateway/blob/8f38c672ee11e6e724fff7b1e430979417fd3ce6/internal/controller/backend_security_policy.go#L106-L108
```
2025-03-02T20:12:23Z    INFO    controller.backend-security-policy      successfully rotated credentials for credentials in namespace default of auth type AWSCredentials, renewing in -0.009733 minutes
```
The requeue time after rotating a set of credentials (AWS in this case) returns a negative number of minutes occasionally.  It requires a manual action/global sync to restart the rotation logic.
Upon further …
> controller: update rotate function to return expiration time

- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
- internal/controller/backend_security_policy.go
- internal/controller/backend_security_policy_test.go
- internal/controller/rotators/aws_oidc_rotator.go
- internal/controller/rotators/aws_oidc_rotator_test.go
- internal/controller/rotators/common.go
- manifests/charts/ai-gateway-helm/values.yaml
Backporting fix for extproc image tag not being sync'd properly and case when requeue is negative.
For more info, please check out:
- controller: fix syncing extproc image tag (https://github.com/envoyproxy/ai-gateway/pull/447)
- controller: update rotate function to return expiration time (https://github.com/envoyproxy/ai-gateway/pull/455)
> backport: fix requeue bug and extproc tag sync

- site/blog/2025-02-25-first-ai-gw-release.md
- site/src/pages/release-notes.md
- site/versioned_docs/version-0.1/getting-started/basic-usage.md
- site/versioned_docs/version-0.1/getting-started/connect-providers/index.md
- site/versioned_docs/version-0.1/getting-started/index.md
- site/versioned_docs/version-0.1/getting-started/installation.md
Released latest patch: https://github.com/envoyproxy/ai-gateway/releases/tag/v0.1.2. Updating site to match!
> site: bump latest patch version v0.1.1 -> v0.1.2

- tests/extproc/testupstream_test.go
- tests/internal/testupstreamlib/testupstream.go
The header to specify the response type (sse, aws, or plain json) was named testupstream.ResponseTypeKey while others are having the standard x-* naming. This fixes the inconsistency and name it `x-response-type`. This was needed to do a fair comparison with LiteLLM that only forwards client headers prefixed with `x-*`.
> chore: consistently name testupstream special keys

- internal/extproc/chatcompletion_processor.go
- internal/extproc/chatcompletion_processor_test.go
- internal/extproc/mocks_test.go
- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_awsbedrock_test.go
- internal/extproc/translator/openai_openai.go
- internal/extproc/translator/openai_openai_test.go
- internal/extproc/translator/translator.go
- tests/extproc/extproc_test.go
- tests/extproc/testupstream_test.go
This fixes a bug in the extproc when handling stream=true requests. Previously, mode_override was set at the request body handling phase, and it was not set in the response headers phase. That resulted in buffering the entire response body which is clearly not ideal as from clients point of view, they will receive the entire streaming vs line by line. This refactors around the mode override and properly handle it.
> extproc: properly stream chat completions

- internal/extproc/chatcompletion_processor.go
- internal/extproc/chatcompletion_processor_test.go
This changes the stat collection behavior so that token latency metrics are only recorded on stream=true requests. This was brought up in an offline discussion and otherwise the metrics doesn't make sense.
#459
> extproc: token latency stat only when stream=true

- .trivyignore
We always use the latest main branch Envoy Gateway, so these CVEs detected by Trivy are false positives. Unfortunately, this is due to the fact that the main branch EG appears as `0.5.0-rc.1-*` in go.mod and there's no way to fix it.
> ci: ignore Envoy Gateway CVEs

- internal/extproc/chatcompletion_processor.go
- internal/extproc/server.go
- internal/extproc/server_test.go
Previously, `filterSensitiveBodyForLogging` resulted in panic when the response was immediate response due to, for example, the matching route was not found.
> extproc: do not panic when immediate response in debug mode

- cmd/extproc/main.go
- cmd/extproc/mainlib/main.go
- examples/extproc_custom_router/main.go
This makes changes to Main function of the extproc so that it will accept context as well as args, etc to allow the callsite to fine tune the behavior of extproc.
Extracted from #458
> extproc: make Main function accept args, stderr

- internal/controller/ai_gateway_route.go
This removes the inconsistent use of logger in AIGatewayRoute controller where it calls `log.FromContext(ctx)` vs all the other places use the properly pre initialized `c.logger`.
> controller: removes inconsistent use of logger

- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_awsbedrock_test.go
AWS Claude 3.5 v1 has cases when assistant returns empty content. Sending that back to AWS will result in a validation error. Will skip adding empty content if string is empty.
```
openai.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'ValidationException:http://internal.amazon.com/coral/com.amazon.bedrock/', 'code': '400', 'message': 'The text field in the ContentBlock object at messages.3.content.0 is blank. Add text to the text field, and try again.'}}
```
#486
> translator: skip adding content if assistant content string is empty

- docs/proposals/002-inference-gateway-support/proposal.md
This adds a proposal doc on the support for Gateway API Inference Extension in Envoy AI Gateway project. This involves the change of the project scope as well as we need to make sure that the existing API layer will co-exist nicely with the GAIE.
Preliminary to #423
> docs: adds high level proposal on GAIE support

- internal/extproc/router/router.go
- internal/extproc/router/router_test.go
Previously, there was a bug in router's code where the matching rule search doesn't break and it iterated over all rules even when there's a matching rule found in the middle. That was a bug in the sense that it is not only an inefficient but also semantically wrong since the last match wins as opposed to the specification of GW API [1] which specifies "If ties still exist within an HTTPRoute, matching precedence MUST be granted to the FIRST matching rule (in list order) with a match meeting the above criteria.".
1: https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.HTTPRouteRule
> extproc: fixes router to make the first match win

- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_awsbedrock_test.go
Ref: (#508)
AWS Claude 3.5 v1 has cases when assistant returns empty content. Sending that back to AWS will result in a validation error. Will skip adding empty content if string is empty.
```
openai.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'ValidationException:http://internal.amazon.com/coral/com.amazon.bedrock/', 'code': '400', 'message': 'The text field in the ContentBlock object at messages.3.content.0 is blank. Add text to the text field, and try again.'}}
```
#486
> backport: skip content if assistant content string is empty

- internal/extproc/server.go
- internal/extproc/server_test.go
- tests/extproc/testupstream_test.go
Previously, /v1/models endpoint returned all header matching values, not limited to the special "x-ai-eg-model" header. This fixes it, and only lists the values from the matching rules using that header.
Follow up on #325
> extproc: do not list non model header values on /models

- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
The scenario where `filterConfig` is nil will result in skipping the code: `d.Template.Spec.Containers[0].Image = c.extProcImage`. The container image should be updated regardless of filterConfig, so moving the logic up.
https://github.com/envoyproxy/ai-gateway/pull/447
> extproc: set extProcImage before potentially returning

- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
The scenario where `filterConfig` is nil will result in skipping the code: `d.Template.Spec.Containers[0].Image = c.extProcImage`. The container image should be updated regardless of filterConfig, so moving the logic up.
https://github.com/envoyproxy/ai-gateway/pull/447
> backport: set extProcImage before potentially returning #515

- examples/extproc_custom_metrics/main.go
- filterapi/x/x.go
- internal/extproc/chatcompletion_processor.go
- internal/extproc/mocks_test.go
- internal/metrics/chat_completion_metrics.go
- internal/metrics/chat_completion_metrics_test.go
Previously, the recently introduced SetBackend API of x.ChatCompletionMetrics was accepting filterapi.Backend by value while the existing Router API returns it by pointer. Since the backend object is allocated prior to the call to the method at config loading time, there's no reason to pass it by value considering the size of the struct.
> extproc: pass backend to SetBackend  by pointer

- tests/extproc/testupstream_test.go
Previously, we did not have any test that checks if the prometheus /metrics endpoint works correctly in the e2e test. This adds an additional test case in tests/extproc.
> test: adds metrics endpoint check in extproc e2e

- cmd/aigw/testdata/translate_basic.out.yaml
- examples/monitoring/README.md
- examples/monitoring/monitoring.yaml
- examples/token_ratelimit/token_ratelimit.yaml
- internal/controller/ai_gateway_route.go
- tests/e2e/e2e_test.go
- tests/e2e/token_ratelimit_test.go
This adds an example prometheus setup to scrape LLM metrics from extproc deployments and the case in tests/e2e to verify it's working.
Contributes to #245
> examples: adds prometheus scraping setup

- internal/controller/backend_security_policy.go
- internal/controller/rotators/aws_oidc_rotator.go
- internal/controller/rotators/aws_oidc_rotator_test.go
This commit ensures that an `apierrors.IsNotFound` is not discarded in the `GetPreRotationTime` method.
Instead, the error is returned to the caller. This commit also updates the `executeRotation` method to
maintain the preexisting behavior by allowing the `apierrors.IsNotFound` case trigger the token rotation.
Fixes #466 
This commit does not add a new test for the `executeRotation` method as the `TestBackendSecurityPolicyController_ReconcileOIDC_Fail` already depends on this behavior.
> controller: surface IsNotFound error in GetPreRotationTime

- site/docs/capabilities/inference-extension.md
This commit fixes the Gateway API Inference Extension doc to refer to the Envoy AI Gateway helm chart (and namespace). I believe it incorrectly refers to Envoy Gateway instead.
> docs: fix helm chart and namespace to match Envoy AI Gateway

- tests/extproc/real_providers_test.go
The test broke after upgrading github.com/openai/openai-go to 0.1.0-beta.6. from 0.1.0-alpha.65 because OpenAI swapped `openai.ToolMessage()`'s two string arguments. :weary:
This change swaps the arguments to use the right order.
compare
https://github.com/openai/openai-go/blob/v0.1.0-alpha.65/chatcompletion.go#L66
and
https://github.com/openai/openai-go/blob/v0.1.0-beta.6/chatcompletion.go#L1420
> test: fix extproc TestWithRealProviders

- cmd/aigw/ai-gateway-default-resources.yaml
- cmd/aigw/envoy-gateway-config.yaml
- cmd/aigw/run.go
- cmd/aigw/run_test.go
- cmd/aigw/translate.go
- go.mod
- go.sum
- internal/extensionserver/extensionserver.go
This fixes `aigw run` command which has been disabled since the refactoring in #599. This requires a couple bug fixes in Envoy Gateway side, so this commit includes the upgrade of the EG as a dependency.
* Closes #607
* Includes envoyproxy/gateway/pull/5984
* Includes envoyproxy/gateway/pull/6020
> cli: fixes aigw run

- .github/workflows/tests.yaml
- tests/e2e/e2e_test.go
EG v1.4.0 has just been released.
> ci: use EG v1.4.0 on e2e test

- cmd/aigw/run.go
- cmd/aigw/run_test.go
- cmd/aigw/testdata/translate_basic.out.yaml
- filterapi/filterconfig.go
- filterapi/filterconfig_test.go
- internal/controller/ai_gateway_route.go
- internal/controller/ai_gateway_route_test.go
- internal/extproc/server.go
- internal/extproc/server_test.go
- tests/extproc/custom_extproc_test.go
- tests/extproc/extproc_test.go
- tests/extproc/real_providers_test.go
- tests/extproc/testupstream_test.go
The backends and headers in filter config are M:N, with https://github.com/envoyproxy/ai-gateway/pull/599, we swapped out the backend from the config.rules, leading to the lost mapping relationship between them. With this PR, we'll move the backends back to the config.rules which is more straightforward.
Related PR: https://github.com/envoyproxy/ai-gateway/pull/620,  https://github.com/envoyproxy/ai-gateway/pull/599
None
> feat: move Backends back to RouteRule

- cmd/aigw/run.go
This fixes a typo in the variable name used in aigw command implementation.
> chore: aigw fakeclient variable name typo

- examples/monitoring/monitoring.yaml
- tests/e2e/basic_test.go
- tests/e2e/e2e_test.go
- tests/e2e/provider_fallback_test.go
- tests/e2e/token_ratelimit_test.go
- tests/e2e/translation_testupstream_test.go
Previously, the pod was the target for port-forwarding. However, that can be fragile since the pod may be rolled out even after the gateway itself becomes healthy after the side car injection. This will deflake the tests by using the service as a target which allows us to avoid choosing the pod that is in the middle of termination/rollout.
Closes #647
> test: deflake e2e by forwarding to svc, not pod

- internal/extproc/chatcompletion_processor.go
This is a hotfix for a bug where if the gzip header is present, we decompress and leave the header. This results in the client throwing an error trying to decompress based on the header, but it has already been decompressed. This hot fix removes the header. In the future we probably want to return it compressed with the header intact. 
for example - the error I encountered was ```io.netty.handler.codec.compression.DecompressionException: Input is not in the GZIP format```
Co-authored-by: Sukumar Gaonkar <sgaonkar4@bloomberg.net>
> extproc: hotfix for gzip header

- internal/extproc/backendauth/aws.go
- tests/extproc/real_providers_test.go
Previously, AWS signing has included the "content-length" header. However, Envoy's extproc filter strips it from the request as we are using CONTINUE_AND_REPLACE option to reduce the memory overhead. While we have still no clue as to why AWS doesn't complain when the request body is small, excluding content-length from the signing target headers will make the tests with both small and large bodies pass.
CONTINUE_AND_REPLACE was introduced in #636 to avoid sending a request body twice between Envoy and the ExtProc.
> backport: do not sign content-length for AWS (#694)

- cmd/aigw/run.go
- cmd/aigw/run_test.go
- site/docs/cli/run.md
Previously, the prometheus metrics port was chosen randomly, hence it was impossible to scrape metrics when using `aigw run` command. This fixes it by using the default port 1064 used by the extproc. Note that there won't be a conflict as `aigw run` doesn't support multiple gateways.
> cli: use fixed prometheus port with aigw run

- .github/workflows/tests.yaml
- CONTRIBUTING.md
- internal/extproc/server.go
- internal/extproc/server_test.go
Until today, macOS binary for Envoy v1.34 was not existent out there, hence there was a workaround codepath for the development purpose. Now, the binary is available with func-e, more precisely hosted via archive-envoy[1] project, it is safe to delete the workaround code.
[1] https://archive.tetratelabs.io/envoy/envoy-versions.json
> extproc: cleans up <v1.34 specific code path

- .github/workflows/tests.yaml
- go.mod
- go.sum
Previously, we haven't run macOS CI since it was a de-facto platform for some maintainers hence it was virtually manually continuously tested. However, we are looking to provide more seamless experience for aigw CLI, it makes sense for us to do the automation of tests on macOS. 
Note that this only enables unit tests and extproc integration test job. The e2e as well as CEL validation tests are not feasible as the nested virtualization is not supported on GHA.
> ci: run unit tests on macos

- internal/controller/backend_security_policy.go
controller: unreconized BackendSecurityPolicyType type caused panic
Fixes: #732
> controller: unsupported BackendSecurityPolicy panic

- .github/PULL_REQUEST_TEMPLATE.md
This cleans up the PR template so that it explicitly says how the title as well as the description is used in the finale commit.
> chore: clean up the PR template

- .github/workflows/retest.yaml
This adds the `retest` action to workflow, we use that in eg repo, this is quite useful for contributors to run /retest in PR if action failed (for flaky issues)
> ci: add retest action

- .github/workflows/build_and_test.yaml
- cmd/aigw/run_test.go
- internal/testing/credentials_context.go
- tests/extproc/envoy.yaml
- tests/extproc/extproc_test.go
- tests/extproc/real_providers_test.go
This adds the following four AI providers in extproc tests:
* Groq https://console.groq.com/docs/openai
* Grok https://docs.x.ai/docs/api-reference#chat-completions
* Samba Nova https://docs.sambanova.ai/cloud/api-reference/endpoints/chat
* Deep Infra https://deepinfra.com/docs/openai_api
> test: adds more AI providers

- cmd/aigw/ai-gateway-default-resources.yaml
- cmd/aigw/run_test.go
Add default admin port for CLI, users can edit by following the example config.
Fixes #686
> cli: add default admin port

- internal/controller/controller.go
- use Install func instead of AddToScheme(Deprecated)
- use from instead of "for" in ApplyIndexing func
None
None
> chore: use Install func instead of AddToScheme(Deprecated)

- internal/extproc/backendauth/aws.go
As we are reverting https://github.com/envoyproxy/ai-gateway/pull/814 to keep using REPLACE_AND_CONTINUE, we need to reverts the commit 92e5202b96f7c1ba17c17bc77a6381412c0175fe to avoid the inclusion of content-length header in the signature with chunked encoding.
> revert: avoid content-length in the signature for AWS

- api/v1alpha1/ai_gateway_route.go
- api/v1alpha1/zz_generated.deepcopy.go
- examples/basic/basic.yaml
- examples/token_ratelimit/token_ratelimit.yaml
- internal/controller/ai_gateway_route.go
- internal/controller/controller.go
- internal/controller/controller_test.go
- manifests/charts/ai-gateway-crds-helm/templates/aigateway.envoyproxy.io_aigatewayroutes.yaml
- manifests/charts/ai-gateway-helm/crds/aigateway.envoyproxy.io_aigatewayroutes.yaml
- site/docs/api/api.mdx
- tests/controller/controller_test.go
- tests/crdcel/main_test.go
- tests/crdcel/testdata/aigatewayroutes/parent_refs.yaml
- tests/crdcel/testdata/aigatewayroutes/parent_refs_default_kind.yaml
- tests/crdcel/testdata/aigatewayroutes/parent_refs_invalid_kind.yaml
- tests/crdcel/testdata/aigatewayroutes/target_refs_with_parent_refs.yaml
This deprecates AIGatwayRoute.spec.targetRefs in favor of parentRefs to comply with the standard of Gateway API. This is a salvation of #580.
Closes #550
> refactor: deprecate targetRefs in favor or parentRefs 

- internal/extproc/server.go
- internal/extproc/server_test.go
- tests/extproc/testupstream_test.go
Previously, unknown path was responded as an internal error as opposed to the fact that it's an 404 with the user input root cause. This fixes the extproc code that way, now that users will be able to know what's wrong with the operation instead of getting the cryptic 500 error.
Contributes to #810
Closes #724
> extproc: return 404 instead of 500 for unknown path

- .github/workflows/build_and_test.yaml
- .github/workflows/docker_build_job.yaml
Replacing `latest` suffix for helm charts and docker image. Replacing suffix with commit message.
#851
> ci: commits to main pushes image/helm with sha suffix

- .github/workflows/docker_build_job.yaml
> ci: fixes docker_build_job.yaml for latest push

- site/docs/capabilities/security/upstream-auth.mdx
> docs: change from Open AI to OpenAI

- Makefile
- tests/e2e/basic_test.go
- tests/e2e/e2e_test.go
- tests/e2e/token_ratelimit_test.go
Due to a missing build tag, previously the golangci-lint hasn't been running for e2e dir. This fixes it.
> chore: enable golangci-lint on e2e dir

- internal/extproc/chatcompletion_processor.go
- internal/extproc/chatcompletion_processor_test.go
- internal/extproc/embeddings_processor_test.go
Aggregating the two metadata namespace under existing one -- `config.metadataNamespace`.
Avoid needing to define more receiving metadata namespace for route.
> extproc: unify metadata namespace

- tests/e2e/inference_pool_test.go
This PR enables inferencepool e2e test by removing tags.
> fix: enable inferencepool e2e test

- internal/extproc/chatcompletion_processor.go
- internal/extproc/chatcompletion_processor_test.go
- tests/extproc/testupstream_test.go
This is a follow up on https://github.com/envoyproxy/ai-gateway/pull/934 to handle the case where the "stream_options" is not present in the first place.
> extproc: force stream_options.include_usage=true part 2

- examples/inference-pool/aigwroute.yaml
- internal/extensionserver/extensionserver_test.go
- internal/extensionserver/post_translate_modify.go
- tests/e2e/inference_pool_test.go
This PR is to disable per-route epp extproc config in direct response route, it makes sure if no route matched, we got a 404 direct response instead of calling unnessary requests to epp ext proc. And added additional e2e tests to verify it.
> fix: disable per-route epp extproc config in direct response

- cmd/aigw/run.go
Previously, there was a flake in the use of bytes.Buffer passed to EG command as well as on our aigw run side, we are reading it concurrently. This fixes it temporarily by passing os.Stdout or io.Discard. 
The race was occasionally happening on CI which was causing the flake, so this fixes it.
> cli: fixes race with EG logs for aigw run

- netlify.toml
Add Kapa and Google Analytics to the CSP settings in Netlify.
Related PR: #949 
Without this setting, the Kapa buttons don't appear on the site.
> site: update CSP setting for Netlify

- cmd/aigw/ai-gateway-default-resources.yaml
- cmd/aigw/testdata/translate_basic.in.yaml
- examples/provider_fallback/base.yaml
- site/docs/capabilities/llm-integrations/connect-providers.md
backendSecurityPolicyRef has been marked deprecated, so this cleans up the remaining reference of backendSecurityPolicyRef in various places.
Follow up on #762
> chore: cleans up the deprecated backendSecurityPolicyRef

- internal/extensionserver/extensionserver_test.go
- internal/extensionserver/post_translate_modify.go
Previously, the extension server implementation treats HTTPRoute not generated by AIGW as an error during the cluster modification phase. That resulted in the errors like below:
```
ERROR   envoy-gateway-extension-server  failed to get AIGatewayRoute object     {"namespace": "default", "name": "non-llm-route", "error": "AIGatewayRoute.aigateway.envoyproxy.io \"non-llm-route\" not found"}
```
In practice, since #963, users can freely attach normal HTTPRoutes in conjunction with AIGatewayRoutes, this switches the log level for that case to Info.
> controller: skipping user-applied HTTPRoute is not an error

- tests/e2e/testupstream_test.go
Non-llm-route tests in TestWithTestUpstream of our E2E test suite has been flaky since #990. This stabilizes it.
> test: deflake TestWithTestUpstream non-llm-route

- api/v1alpha1/ai_gateway_route.go
- site/docs/api/api.mdx
This commit adds missing `+optional` annotations which resulted in incorrectly marking some fields "required" in the generated API documentation.
> api: adds missing +optional annotations for optionals

- internal/extproc/chatcompletion_processor.go
- internal/extproc/chatcompletion_processor_test.go
- internal/extproc/embeddings_processor.go
- internal/extproc/embeddings_processor_test.go
- internal/extproc/mocks_test.go
- internal/extproc/translator/openai_awsbedrock.go
- internal/extproc/translator/openai_embeddings.go
- internal/extproc/translator/openai_gcpanthropic.go
- internal/extproc/translator/openai_gcpvertexai.go
- internal/extproc/translator/openai_gcpvertexai_test.go
- internal/extproc/translator/openai_openai.go
- internal/extproc/translator/translator.go
- internal/extproc/translator/translator_test.go
- internal/extproc/util.go
- internal/extproc/util_test.go
This lifts the error status code from each translators into the processors level so that we could share the same logic and won't need to copy paste anymore.
> extproc: lift error status handling from translators 

- tests/internal/envtest.go
This switches to use CRDs from EG's Chart to avoid manually maintaining GWAPI version as well as manually list necessary components.
> test: updates CRDs used in envtest

- api/v1alpha1/ai_gateway_route.go
- manifests/charts/ai-gateway-crds-helm/templates/aigateway.envoyproxy.io_aigatewayroutes.yaml
- manifests/charts/ai-gateway-helm/crds/aigateway.envoyproxy.io_aigatewayroutes.yaml
- site/docs/api/api.mdx
This updates the documentation on AIGatewayRoute to reflect the correct information. Notably, EnvoyExtensionPolicy is no longer generated.
> api: removes obsolete comment on AIGatewayRoute

- internal/extproc/chatcompletion_processor.go
- internal/extproc/translator/openai_embeddings.go
- internal/extproc/translator/openai_embeddings_test.go
- internal/extproc/translator/openai_openai.go
- internal/extproc/translator/openai_openai_test.go
- internal/extproc/translator/translator.go
- tests/extproc/testupstream_test.go
- tests/internal/testenvironment/test_environment.go
There was a bug in the translation of OpenAI->OpenAI layer where the body mutation is broken when forceBodyMutation = true. forceBodyMutation becomes true when stream_options is not present in the original body and we lacked the test case for it. 
Closes #1017
> extproc: fixes modelNameOverride + forced stream_options

- .github/dependabot.yml
I noticed that the commit history of the repository is confusing due to a large number of dependabot PRs. We also see many cancelled CI runs show up as red x's, which isn't necessarily a problem but just something.
I couldn't think of a reason to group only `k8s.io` and `golang.org` and not group any other dependencies - they'll all be merged anyways. So this proposes grouping them all so you have one PR for Go and one PR for node per dependabot run.
If this is not desired, I can rework this to at least just a bugfix of the react grouping, which currently doesn't do anything since it's under `gomod` instead of `npm` block
> chore: group all dependabot updates

- site/docs/capabilities/observability/tracing.md
This corrects the Phoenix instructions to use the default storage PostgreSQL. Most users will have a StorageClass available in their cluster, so won't fail.
Fixes #1070
> fix: correct phoenix docs by defaulting to postgresql

- cmd/aigw/run.go
Previously, there was a slight possibility that the config writes are not flushed by the time when EG starts running. This fixes it.
Closes #1059
> cli: fixes race during config writes on pre-startup

- .github/workflows/release.yaml
Docker build template got renamed a while back, so this fixes it.
> ci: fixes release workflow

- cmd/aigw/ai-gateway-default-resources.yaml
- cmd/aigw/ai-gateway-local.yaml
- cmd/aigw/config_test.go
- cmd/aigw/docker-compose-otel.yaml
- cmd/aigw/docker-compose.yaml
- cmd/aigw/run.go
- cmd/aigw/run_test.go
- go.mod
- go.sum
- site/docs/cli/run.md
Before, we had to make different copies of config files in order to make small changes like to the ollama host or the model in use. This now implements ENV substitution.
Example:
```diff
--- default.yaml        2025-03-26 11:27:30
+++ custom.yaml 2025-03-26 11:28:55
@@ -115,9 +115,9 @@
- matches:
- headers:
- type: Exact
name: x-ai-eg-model
-              value: mistral:latest
+              value: ${CHAT_MODEL:=deepseek-r1:1.5b}
```
This uses the special "127.0.0.1.nip.io" hostname in *local* configs, which allows ENV substitution to work with docker vs normal go. This requires Ollama to be started with OLLAMA_HOST=0.0.0.0, which was already documented in the README. The ENV variables OPENAI_HOST and OPENAI_PORT allows use …
> feat: allow env variable substitution in CLI config

- .gitignore
Add .claude/ directory, .env, and .mcp.json to .gitignore to prevent committing Claude Code settings and generated files.
> chore: exclude Claude Code settings from git

- .github/workflows/pr_style_check.yaml
This removes the length check in the PR title. This has existed to enforce the single format of commit message but it was too restrict and has been annoying to be honest.
> ci: removes PR title length check

- .github/workflows/build_and_test.yaml
test_e2e_inference_extension was missing from the "needs" list for publication of docker images.
> ci: require inference extension test to pass before publish

- .github/workflows/release.yaml
- site/docs/cli/installation.md
Build the `aigw` CLI binaries as part of the release process and attaches them as release artifacts.
Fixes https://github.com/envoyproxy/ai-gateway/issues/1064
N/A
> ci: attach aigw cli artifacts to the releases

- .github/workflows/docker_build_job.yaml
- Dockerfile
- Makefile
- site/docs/cli/installation.md
Generate Docker images for the `aigw` command.
To run it with the default config, only the port and the required credential environment variables need to be configured. For example:
```
$ docker run --rm -p 1975:1975 -e TARS_API_KEY=$TARS_API_KEY envoyproxy/ai-gateway-cli run
looking up the latest Envoy version
downloading https://archive.tetratelabs.io/envoy/download/v1.35.0/envoy-v1.35.0-linux-arm64.tar.xz
starting: /tmp/envoy-gateway/versions/1.35.0/bin/envoy in run directory /tmp/envoy-gateway/runs/1756912322973222887
```
Follow-up of: https://github.com/envoyproxy/ai-gateway/pull/1154#issuecomment-3248126209
N/A
> cli: generate Docker images for the aigw command

- .github/workflows/build_and_test.yaml
When using path filtering to prevent workflows from executing, the GHA required jobs are never satisfied, blocking PRs from being merged. Instead of using path filtering, this PR uses the `path-filter` action to overcome this limitation and have the required jobs (ci-required) always report a status.
N/A
N/A
> ci: properly configure dependencies for required jobs

- .github/workflows/build_and_test.yaml
Update the CI test job to poll the Ollama port until it is open (waiting up to 30 seconds at most). This is a less flaky approach than just waiting 10 seconds, then continuing.
N/A
N/A
> ci: better wait for the ollama port in test job

- internal/extproc/translator/anthropic_gcpanthropic.go
- internal/extproc/translator/anthropic_gcpanthropic_test.go
Usage event were parsed as raw json instead of event type + json.
Example of stream chunks:
```
event: message_start
data: {"type":"message_start","message":{"id":"msg_vrtx_01V4HwqjNGwvFRqBVuhQNCXW","type":"message","role":"assistant","model":"claude-sonnet-4-20250514","content":[],"stop_reason":null,"stop_sequence":null,"usage":{"input_tokens":20,"cache_creation_input_tokens":0,"cache_read_input_tokens":0,"output_tokens":1}}  }
event: ping
data: {"type": "ping"}
event: content_block_start
data: {"type":"content_block_start","index":0,"content_block":{"type":"text","text":""}}
event: content_block_delta
data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"There"}}
```
> fix: gcp anthropic streaming usage

- .licenserc.yaml
- cmd/aigw/.env.otel.console
- cmd/aigw/.env.otel.otel-tui
- cmd/aigw/.env.otel.phoenix
- cmd/aigw/README.md
- cmd/aigw/docker-compose-otel.yaml
- cmd/extproc/mainlib/main.go
- cmd/extproc/mainlib/main_test.go
- go.mod
- internal/internalapi/internalapi.go
- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
- internal/testing/testotel/collector.go
- internal/tracing/tracing.go
- internal/tracing/tracing_test.go
- site/docs/capabilities/observability/tracing.md
- site/docs/cli/run.md
- tests/extproc/testupstream_test.go
- tests/extproc/vcr/docker-compose-otel.yaml
- tests/extproc/vcr/otel_chat_completions_test.go
- tests/extproc/vcr/otel_metrics_test.go
- tests/extproc/vcr/prometheus_metrics_test.go
- tests/internal/testopeninference/Dockerfile.openai_client
This extends otel ENV config to metrics, when enabled exports instead of a prometheus listener. This allows metrics in otel native systems like elastic stack, otel tui and otherwise, without a prometheus pump. This also allows you to do ad-hoc configuration by using `console` config.
Here's an example of standalone using otel-tui https://github.com/ymtdzzz/otel-tui:
Updated cmd/aigw examples:
- Add otel-tui service to show native otel w/o prometheus
- Use profile-based env file selection (.env.otel.${COMPOSE_PROFILES:-console})
- Set console as default for immediate debugging without external dependencies
Documentation:
- Document separate OTLP endpoints for traces/metrics and exporter types
Phoenix users: Set OTEL_METRICS_EXPORTER=none as Phoenix only supports traces …
> feat(metrics): support otel and console metric export

- Dockerfile
- cmd/aigw/.env.otel.console
- cmd/aigw/README.md
- cmd/aigw/ai-gateway-default-resources.yaml
- cmd/aigw/ai-gateway-local.yaml
- cmd/aigw/docker-compose-otel.yaml
- cmd/aigw/docker-compose.yaml
- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
- internal/metrics/nonempty_exporter.go
- internal/metrics/nonempty_exporter_test.go
- internal/tracing/tracing.go
- site/docs/cli/installation.md
This combines a fix of console metrics with a drift fix of our docker setup.
Notably, this sorts out console metrics which formerly ignored temporality and
also emitted updates to the console regardless of if there were any data points.
This is a problem upstream as the console reporter isn't very sophisticated. The
behavior desired was easy enough, so I sorted it out here.
Next, our docker examples weren't using our docker images, yet. So, this uses
them and is careful about `--build` so that people know if they do that, how to
make sure the image is indeed fresh.
Together, these changes make the console example quite reasonable as a debugging tool.
```bash
$ docker logs aigw -f
looking up the latest patch for Envoy version 1.35
1.35.3 is already downloaded
starting: …
```
> feat(metrics): fix console metrics and make aigw examples use official images

- tests/extproc/envoy.yaml
- tests/extproc/real_providers_test.go
`gemini-embedding-exp-03-07` is being deprecated by Google.
> test: use gemini-embedding-001 for Gemini Embeddings test

- cmd/aigw/README.md
- cmd/aigw/docker-compose.yaml
- cmd/aigw/run_test.go
- internal/testing/ports.go
- tests/e2e/token_ratelimit_test.go
- tests/internal/testenvironment/test_environment.go
This fixes a flake in e2e where we used require.XXX assertion inside an Eventually block which failed when there were no metrics, yet, causing the loop to not proceed again. Instead, we loop on no metrics yet.
This also addresses a configuration issue where we passed 0 as the admin port causing an unknown ephemeral one to be used. This changes the test to pick one for the admin, so that later assertions can be made against it.
A later change will attempt to make all aigw tests assertable ports, but for now this fixes the admin one.
> ci: fix e2e metrics flake and better handle ports in aigw tests

- Makefile
- tools/go.mod
Replaces manual invocation of gci and gofumpt with `golangci-lint fmt` which is effectively the same
I happened to notice that gci / gofumpt were being directly invoked, but since v2 golangci-lint has a formatting command for the configured formatters. It just applies the formatters without any compilation, etc and is fast and equivalent
> ci: format Go with golangci-lint

- .github/workflows/build_and_test.yaml
Previously, test_e2e_aigw was not skipped unlike others when there's only doc changes in the PR. Also, it was not required in the docker build&push on the main branch, so this commit fixes these two issues.
> ci: skip test_e2e_aigw on doc chaneg & fix docker job requirement

- cmd/controller/main.go
- cmd/controller/main_test.go
- manifests/charts/ai-gateway-helm/templates/deployment.yaml
- manifests/charts/ai-gateway-helm/values.yaml
Makes go's gRPC `MaxRecvMsgSize` configurable for the extension server, whose default value is 4MB https://pkg.go.dev/google.golang.org/grpc#MaxRecvMsgSize
When the gRPC message payload from the xDS server exceeds 4MB, it is rejected by the extension server and the below errors is observed on envoy-gateway:
```
2025-10-07T10:26:44.625Z        ERROR   xds     runner/runner.go:245    failed to translate xds ir      {"runner": "xds", "error": "rpc error: code = ResourceExhausted desc = grpc: received message larger than max (6683527 vs. 4194304)"}
2025-10-07T10:26:44.625Z        ERROR   watchable       message/watchutil.go:86 observed an error       {"runner": "xds", "error": "rpc error: code = ResourceExhausted desc = grpc: received message larger than max (6683527 vs. …
```
> fix: makes gRPC's MaxRecvMsgSize for the extension server

- internal/mcpproxy/handlers.go
- internal/testing/testotel/collector.go
- internal/tracing/mcp.go
- internal/tracing/mcp_test.go
- tests/extproc/mcp/env.go
- tests/extproc/mcp/mcp_test.go
Before everything was vaguely "mcp.request" which is not untrue, but not helpful. There are plenty of low-cardinality choices for span or metric names and the `req.Method` is the most intuitive. This uses the same naming conventions as mcp-go
> fix: make mcp span names informative
